force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Show True and False sign depending upon the Account Status.
#RQ-000998 : Formula edited to include condition for Non Shipping account</description>
    <formula>IF(   ISPICKVAL(SCV_Status__c , &apos;Active&apos; ) ||  RecordTypeId ==  $Label.Non_shipping_Party_Account_RecordType_Label  , IMAGE(&quot;/resource/Green_Tick&quot;,&quot;Active&quot;, 13, 13) , IMAGE(&quot;/resource/Red_Cross&quot;,&quot;InActive&quot; , 13, 13) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Displays a visual indicator of whether or not this Account&apos;s Status in SCV. A red cross is &quot;Inactive&quot;, a green tick is &quot;Active&quot;.</inlineHelpText>
    <label>Active</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Client Accounts are customers who place bookings with the company and WILL have an SCV code. Client Accounts are mastered in SCV.</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/classes/Batch_ClosePastOpps_Test.cls
/**
 * 1.0     SFSE-8515  15-Dec-2022  Jothsana Devi          Test class for Batch_OpptyCloseDateChatterNotification (for chatter notification)
 * 2.0     SFSE-11001 18-sep-2022  ramya                  upgraded to latest framework
*/
@isTest
private class Batch_ClosePastOpps_Test {
    static testmethod void Setup() {
       
        TriggerExecutionController.skipAllTriggers(true);

    Validation_Rules_Bypass__c newRecord = new Validation_Rules_Bypass__c();
    newRecord.Active__c = true;
    newRecord.SetupOwnerId = UserInfo.getUserId();
    insert newRecord;

    Account clientAccount = TestBusinessHelper.createAccount('Client_Account', true);
    Opportunity mslOppty = TestBusinessHelper.createOpportunity(clientAccount, null, null, 'ShippingCargoServices', BrandUtilities.MAERSKLINE, true);
    mslOppty.CloseDate = Date.today().addDays(-90);
    update mslOppty;

    newRecord.Active__c = false;
    newRecord.SetupOwnerId = UserInfo.getUserId();
    update newRecord;

    TriggerExecutionController.skipAllTriggers(false);     
   }    
    @IsTest(SeeAllData=true)
    static void testBatch_CloseDateDueIn7Days(){
        Test.startTest();
        Database.executeBatch(new Batch_ClosePastOpps(), 500);
        Test.stopTest();
        
    }
}