force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Show True and False sign depending upon the Account Status.
#RQ-000998 : Formula edited to include condition for Non Shipping account</description>
    <formula>IF(   ISPICKVAL(SCV_Status__c , &apos;Active&apos; ) ||  RecordTypeId ==  $Label.Non_shipping_Party_Account_RecordType_Label  , IMAGE(&quot;/resource/Green_Tick&quot;,&quot;Active&quot;, 13, 13) , IMAGE(&quot;/resource/Red_Cross&quot;,&quot;InActive&quot; , 13, 13) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Displays a visual indicator of whether or not this Account&apos;s Status in SCV. A red cross is &quot;Inactive&quot;, a green tick is &quot;Active&quot;.</inlineHelpText>
    <label>Active</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cluster_Name__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>+++ INTEGRATION: SCV, Business_Intelligence +++
#RQ-000235 - Help text added.
#RQ-005677 - Deprecated</description>
    <inlineHelpText>Cluster ownership based on MSL Account owner.</inlineHelpText>
    <label>z_Cluster</label>
    <referenceTo>BDA__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>+++ INTEGRATION: SCV +++</description>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Filtered Lookup Error: The specified &quot;Country&quot; is not of type &quot;Country&quot;.</errorMessage>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Accounts (Country)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MCC_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MCC_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0047: 
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.</description>
    <inlineHelpText>The MCC Line sales person responsible for this Account.</inlineHelpText>
    <label>MCC Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MLL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MLL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0054: Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.</description>
    <inlineHelpText>The MLL sales person responsible for this Account.</inlineHelpText>
    <label>MLL Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.MLL__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MSL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MSL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#Safmarine_United
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.
#RQ-004168 - Updated FLS</description>
    <inlineHelpText>The Maersk Line sales person responsible for this Account.</inlineHelpText>
    <label>Maersk Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_MSL_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Represents_Concern__c.field-meta.xml
<CustomField>
    <fullName>Represents_Concern__c</fullName>
    <defaultValue>false</defaultValue>
    <description>#RQ-004705
As part of the interim solution will create a new field called &quot;Represents Concern&quot; and this is to show the equivalent of the &quot;Is-Concern&quot; relationship that master data will have</description>
    <inlineHelpText>When set to true this highlights that this SCV code is the equivalent of the concern level account</inlineHelpText>
    <label>Represents Concern</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>SCL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#Safmarine_United
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.
#RQ-004168 - Updated FLS</description>
    <inlineHelpText>The Safmarine sales person responsible for this Account.</inlineHelpText>
    <label>z_Safmarine Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_SCL_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration&quot; .
Unique customer number shared across numerous Maersk systems. Populated by custom Java components in the middleware layer. Should be read-only to users using FLS so there is no chance of modification by anyone other than the Master Data Interface User.
#RQ-002042-Reduced the text characters to 11
#RQ-004927.</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal system identifier from SCV</inlineHelpText>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Status__c.field-meta.xml
<CustomField>
    <fullName>SCV_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot;
#RQ-000235 - Help text added.
#RQ-004162 - Changed Field label and help text
#RQ-004927.</description>
    <inlineHelpText>Indicates if this customer is active or not as per Customer Master Data definitions</inlineHelpText>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SEA_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>SEA_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0031_2 - Sealand Integration. This field is used to store the sealand account Owner</description>
    <inlineHelpText>The SeaLand sales person responsible for this Account.</inlineHelpText>
    <label>Sealand Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_SEA_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Seago_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Seago_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0055 - Seago Line Integration. This field is used to store the Seago Line Account Owner. 
#RQ-003201 - Look into the current Apex Errors we are receiving.</description>
    <inlineHelpText>The Seago Line sales person responsible for this Account.</inlineHelpText>
    <label>Seago Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_SGL_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Unassigned.recordType-meta.xml
<RecordType>
    <fullName>Unassigned</fullName>
    <active>true</active>
    <description>Unassigned Accounts are dummy Accounts used for budgeting and targeting purposes and are not real customers.</description>
    <label>Unassigned</label>
</RecordType>

force-app/main/default/classes/AccountDataHelper_Test.cls
/**
* Helper class for generating Test data for all types of Account.

* Date         Owner                                   Description
**************************************************************************************************************************************
* 14/10/2014   Deepa.Raman@ust-global.com              #RQ-000917 Move ALL test data generation to Helper classes.
* 20/11/2015   meghana.gupta@ust-global.com            #RQ-002192 Use Maersk Id fields to populate Export/Import Reps or Owner fields
* 02/12/2015   Sunu.Paul@ust-global.com                #PR-0055-Added MLL,MCC,Seago Account Owners. 
* 10/02/2016   Sunu.Paul@ust-global.com                #RQ-002978-Added SuperUser
* 31/03/2016   Madhava.kotte@ust-global.com            #RQ-002301:OpportunityTrigger Refactoring
* 30/03/2017   Nisha.arjunan@ust-global.com            #RQ-005057 Updated createNonShippingPartyAccount(), return nonShipPartyAccount instead of draftAccount, fix
* 25/09/2017   Uvais.Komath@ust-global.com             #RQ-005677 Removed reference to Account.Cluster_Name__c sa part of field deprecation
* 23/09/2019    Neha -TCS                              #RQ-007086Removed the limit 6 from Query at line 61 where Account Record type are being queries since now there are 7 record types.
* 12-Nov-2019  manjunath@maersk                        #RQ-012362 Removed reference of Account.Commercial_Leader__c
* 3-June - 2020 Rakesh@maersk                           #SFSE-397   Inserting Geography record
*/
        
public class AccountDataHelper_Test {          
   
    public static Account clientAccount = null;
    public static Account concernAccount = null;
    public static Account unAssignedAccount = null;
    public static Account draftAccount = null;
    public static Account nonShipPartyAccount = null ;
    public static User integrationTestUser = null;
    public static Account testAccountMSL,testAccountSEA,testNamedAccount;
    public static AccountTeamMember acctMbrObj,acctMbrSEAObj;
    public static Bda__c bdObj = null;
   
    //Call method to create Test Users
    static 
    {
        if (UserDataGeneratorHelper_Test.integrationUser == null){
            
            UserDataGeneratorHelper_Test.initializeIntegrationUser();  
        
        }
        
        if ( UserDataGeneratorHelper_Test.salesUser == null){
            
            UserDataGeneratorHelper_Test.initializeSalesUser();
        
        }
        
        /*if ( UserDataGeneratorHelper_Test.SuperUser == null){//#RQ-002978
            
        UserDataGeneratorHelper_Test.initializeSuperUser();//#RQ-002978
         
        }*///#RQ-002978
        //UserDataGeneratorHelper_Test.initializeSystemAdminUser();
    } 
    
    
    
    
    /**
    * Method to get Record Types of Account to create Accounts.
    **/ 
    public static Map<String, ID> getAccountRecordType () {
    
        Map<String, ID> accRT = new Map<String, ID> ();
        /*for(RecordType r : [SELECT Id, Name FROM RecordType WHERE sObjectType = 'Account']) {
            accRT.put(r.Name, r.Id);
        }*/
        Schema.DescribeSObjectResult accountDescribe = Account.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> rtInfo = accountDescribe.getRecordTypeInfos();
        for(Schema.RecordTypeInfo recordtype : rtInfo){
            accRT.put( recordtype.name , recordtype.getRecordTypeId());
        }
        return accRT;
    }
    
    public static Map<String, ID> accountRecordTypeMap = getAccountRecordType ();  
    
    
    /**
    * Method to create Client Account
    **/     
    /*
    public static Account createClientAccount(){   
    
        clientAccount = createClientAccount( null, 'Active');
        return clientAccount;

    }
    
    public static Account createClientAccount( Id bdaId, String scvStatus ){ 
    
        system.debug('####### Inside createClientAccount');
    
        clientAccount = new Account ();        
        clientAccount.Name = 'Test Class Client Account';
        clientAccount.Type = 'BCO' ;
        clientAccount.SCV_Code__c = '11223344';
        clientAccount.SCV_Status__c = scvStatus;
        clientAccount.RecordTypeId = accountRecordTypeMap.get('Client Account');
        
       clientAccount.MSL_Export_Rep_Maersk_Id__c  = UserDataGeneratorHelper_Test.MSLsalesUser.Maersk_User_Id__c  ;  //Export Rep for MSL  is auto-populated based on this field
       clientAccount.SCL_Export_Rep_Maersk_Id__c  = UserDataGeneratorHelper_Test.SCLsalesUser.Maersk_User_Id__c ;        
       clientAccount.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAsalesUser.id ; //Brand Account Owner for SEA 
       clientAccount.MCC_Account_Owner__c = UserDataGeneratorHelper_Test.MCCIntegrationUser.id;//Brand Account Owner for MCC//#PR-0055 
       clientAccount.MLL_Account_Owner__c = UserDataGeneratorHelper_Test.MLLIntegrationUser.id;  //Brand Account Owner for MLL//#PR-0055   
       clientAccount.Seago_Account_Owner__c = UserDataGeneratorHelper_Test.SeagoIntegrationUser.id;//Brand Account Owner for Seago//#PR-0055      
        
        if (bdaId != null){
            
            clientAccount.Cluster_Name__c = bdaId;
        
        }
        
        System.runAs(UserDataGeneratorHelper_Test.integrationUser){
        
            insert clientAccount;
        
        }
        
        return clientAccount;
    }
    */
    public static Account createClientAccount(){   
    
        clientAccount = createClientAccount( null, 'Active', '10000045402');
        return clientAccount;

    }
    public static Account createClientAccount( Id bdaId, String scvStatus ){ 
        
        clientAccount = createClientAccount( bdaId, scvStatus, null );
        return clientAccount;    
        
    }
    
     public static Account createClientAccountwithCountry( Id bdaId, String scvStatus, id geoid ){ 
    
        system.debug('####### Inside createClientAccount');
    
        clientAccount = new Account ();        
        clientAccount.Name = 'Test Class Client Account';
        clientAccount.Type = 'BCO' ;
        clientAccount.SCV_Status__c = scvStatus;
        clientAccount.RecordTypeId = accountRecordTypeMap.get('Client Account');
        clientAccount.Country__c = geoid;
        
       clientAccount.MSL_Account_Owner__c  = UserDataGeneratorHelper_Test.MSLsalesUser.Id  ;  
       //clientAccount.SCL_Account_Owner__c  = UserDataGeneratorHelper_Test.SCLsalesUser.Id ;        
       clientAccount.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAsalesUser.id ; //Brand Account Owner for SEA 
       clientAccount.MCC_Account_Owner__c = UserDataGeneratorHelper_Test.MCCIntegrationUser.id;//Brand Account Owner for MCC//#PR-0055 
       clientAccount.MLL_Account_Owner__c = UserDataGeneratorHelper_Test.MLLIntegrationUser.id;  //Brand Account Owner for MLL//#PR-0055   
       clientAccount.Seago_Account_Owner__c = UserDataGeneratorHelper_Test.SeagoIntegrationUser.id;//Brand Account Owner for Seago//#PR-0055      
       /*
        if (bdaId != null){
            
            clientAccount.Cluster_Name__c = bdaId;
        
        }
        */
        System.runAs(UserDataGeneratorHelper_Test.integrationUser){
        
            insert clientAccount;
        
        }
        
        return clientAccount;
    }


    public static Account createClientAccount( Id bdaId, String scvStatus, String SCVCode ){ 
    
        system.debug('####### Inside createClientAccount');
        insert new Geography__c(Name='London', Active__c =true);    //#SFSE-397
        clientAccount = new Account ();        
        clientAccount.Name = 'Test Class Client Account';
        clientAccount.Type = 'BCO' ;
        clientAccount.SCV_Code__c = SCVCode;
        clientAccount.SCV_Status__c = scvStatus;
        clientAccount.RecordTypeId = accountRecordTypeMap.get('Client Account');
        clientAccount.BillingCity = 'London';
        clientAccount.BillingStreet = 'test street 123';
        clientAccount.MSL_Account_Owner__c  = UserDataGeneratorHelper_Test.MSLsalesUser.Id  ;  
        //clientAccount.SCL_Account_Owner__c  = UserDataGeneratorHelper_Test.SCLsalesUser.Id ;        
        clientAccount.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAsalesUser.id ; //Brand Account Owner for SEA 
        clientAccount.MCC_Account_Owner__c = UserDataGeneratorHelper_Test.MCCIntegrationUser.id;//Brand Account Owner for MCC//#PR-0055 
        clientAccount.MLL_Account_Owner__c = UserDataGeneratorHelper_Test.MLLIntegrationUser.id;  //Brand Account Owner for MLL//#PR-0055   
        clientAccount.Seago_Account_Owner__c = UserDataGeneratorHelper_Test.SeagoIntegrationUser.id;//Brand Account Owner for Seago//#PR-0055      
        clientAccount.Represents_Concern__c= true;
        
        /*
        if (bdaId != null){
            
            clientAccount.Cluster_Name__c = bdaId;
        
        }
        */
        System.runAs(UserDataGeneratorHelper_Test.integrationUser){
        
            insert clientAccount;
        
        }
        
        return clientAccount;
    }

    
    
     //To create client account with MSL user
    public static void createClientAccountWithMSLUser(){
        System.debug('###### inside helper');
        testAccountMSL = new Account ();
        testAccountMSL.Name = 'Test Account - MSL User';
        testAccountMSL.Type = 'BCO' ;
        testAccountMSL.RecordTypeId = accountRecordTypeMap.get('Client Account');
        testAccountMSL.Owner = UserDataGeneratorHelper_Test.MSLIntegrationUser; //Account owner as MSL user            
        System.runAs(UserDataGeneratorHelper_Test.MSLIntegrationUser){
            
            Database.insert(testAccountMSL);
            
        }
        
    }
    
    public static Account createClntAccountWithMSLUser(){
        createClientAccountWithMSLUser();
        return testAccountMSL;
    }
    //RQ-004168
    //To create client account with MSL user
    public static void createClientNamedAccount(){
        testNamedAccount = new Account ();
        testNamedAccount.Name = 'Test Account - MSL User';
        testNamedAccount.Type = 'BCO' ;
        testNamedAccount.RecordTypeId = accountRecordTypeMap.get('Client Account');
          
        testNamedAccount.MSL_Account_Owner__c  = UserDataGeneratorHelper_Test.MSLsalesUser.Id  ;  //Export Rep for MSL  is auto-populated based on this field
        //testNamedAccount.SCL_Account_Owner__c  = UserDataGeneratorHelper_Test.SCLsalesUser.Id ;        
        testNamedAccount.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAsalesUser.id ; //Brand Account Owner for SEA 
        testNamedAccount.MCC_Account_Owner__c = UserDataGeneratorHelper_Test.MCCIntegrationUser.id;//Brand Account Owner for MCC//#PR-0055 
        testNamedAccount.MLL_Account_Owner__c = UserDataGeneratorHelper_Test.MLLIntegrationUser.id;  //Brand Account Owner for MLL//#PR-0055   
        testNamedAccount.Seago_Account_Owner__c = UserDataGeneratorHelper_Test.SeagoIntegrationUser.id;//Brand Account Owner for Seago//#PR-0055      
        testNamedAccount.Owner = UserDataGeneratorHelper_Test.MSLIntegrationUser; //Account owner as MSL user            
        System.runAs(UserDataGeneratorHelper_Test.MSLIntegrationUser){
            Database.insert(testNamedAccount);
             
        }
        
    }
    
    // create test account for invalid sceanrio testing
    public static Account createInvalidTestAccount( Id bdaId ){
        
        clientAccount = new Account ();        
        clientAccount.Name = 'Test Account Invalid';
        clientAccount.Type = 'BCO' ;
        clientAccount.SCV_Code__c = '11223344';
        clientAccount.SCV_Status__c = 'Active';
        clientAccount.RecordTypeId = accountRecordTypeMap.get('Client Account');
        /*
        clientAccount.Cluster_Name__c = bdaId;
        */
        System.runAs(UserDataGeneratorHelper_Test.IntegrationUser){
            
            Database.insert( clientAccount );
            
        }
        return clientAccount;
    }   
    
    //To create client account with Sealand  & Integration users
    public static void createClientAccountWithSealandUSer(){
        
        testAccountSEA = new Account ();
        testAccountSEA.Name = 'Test Account - Sealand and Integration Users';
        testAccountSEA.Type = 'BCO' ;
        testAccountSEA.RecordTypeId = accountRecordTypeMap.get('Client Account');
        testAccountSEA.Owner = UserDataGeneratorHelper_Test.SEAIntegrationUser;  //Account owner as SEA user   
        testAccountSEA.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAIntegrationUser.Id; 
        System.runAs(UserDataGeneratorHelper_Test.SEAIntegrationUser){
            
            Database.insert(testAccountSEA);
            
        }
        createAccountTeamMemberWithIntegrationUser();
    }        
   
     //To create account team member with integration user in Sealand account
    public static void createAccountTeamMemberWithIntegrationUser(){
    
        acctMbrSEAObj = new AccountTeamMember(); 
        acctMbrSEAObj.AccountId = testAccountSEA.Id;
        acctMbrSEAObj.TeamMemberRole = 'Team Member';
        acctMbrSEAObj.userId = UserDataGeneratorHelper_Test.integrationUser.id;  
      
        System.runAs(UserDataGeneratorHelper_Test.integrationUser){
            
            Database.insert(acctMbrSEAObj);
            
        }
        
    }
    /**
    * Method to create Concern Account
    **/   
    //RQ-004168
    public static Account createConcernAccount(){
        system.debug('#### Creating Concern Account');
        concernAccount = new Account ();       
        
        concernAccount.Name = 'Test Class Client Account';
        concernAccount.SCV_Code__c = '***22572';    //SCV code for concern Account starts with ***
        concernAccount.SCV_Status__c = 'Active';
        concernAccount.RecordTypeId = accountRecordTypeMap.get('Concern Account');
        concernAccount.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAsalesUser.id ; //Brand Account Owner for SEA
        concernAccount.MSL_Account_Owner__c = UserDataGeneratorHelper_Test.MSLsalesUser.id ;
        //concernAccount.SCL_Account_Owner__c = UserDataGeneratorHelper_Test.SCLsalesUser.id ;     
       
        //concernAccount.Account_Manager_Maersk_Id__c = UserDataGeneratorHelper_Test.salesUser.Maersk_User_Id__c ;  //Account manager.            
            
        System.runAs( UserDataGeneratorHelper_Test.integrationUser ){
        
            insert concernAccount;
        
        }
        
        system.debug( '####  Concern Account created--' + concernAccount.id );
        return concernAccount;       
        
    }
    
    /**
    * Method to create Unassigned Account
    **/     
    public static Account createUnassignedAccount(){

        unAssignedAccount = new Account ();

        unAssignedAccount.Name = 'Internal Global Address Book 321312';
        unAssignedAccount.Type = 'BCO' ;
        unAssignedAccount.RecordTypeId = accountRecordTypeMap.get('Unassigned');

        System.runAs(UserDataGeneratorHelper_Test.SEAintegrationUser){
            insert unAssignedAccount;
        }
    
         return unAssignedAccount;
    } 
    
    
    
    /**
    * Method to create Draft Account
    **/ 

    public static Account createDraftAccount(){
    
        createDraftAccount(UserDataGeneratorHelper_Test.integrationUser);              
        return draftAccount;
        
    }
    
    public static Account createDraftAccount( User RunAsUser ){
        
        draftAccount = new Account ();
        draftAccount.Name = 'Test Class Draft Account';
        draftAccount.RecordTypeId = accountRecordTypeMap.get( 'Draft Account' );

        System.runAs( RunAsUser ){
            
            insert draftAccount;
        
        }
        
        return draftAccount;
    }
    
    /**
    * Method to create Non-shipping Party Account 
    **/  
    public static Account createNonShippingPartyAccount(){

        nonShipPartyAccount = new Account ();

        nonShipPartyAccount.Name = 'Test Class Non Shipping Party Account';
        nonShipPartyAccount.RecordTypeId = accountRecordTypeMap.get('Non-shipping Party Account');

        System.runAs(UserDataGeneratorHelper_Test.integrationUser){
            insert nonShipPartyAccount;
        }
        
        return nonShipPartyAccount;
    }  
    
    //To create account team member
    public static AccountTeamMember createAccountTeamMember( Id AccountId , Id UserId, String TeamMemberRole ){
                
        AccountTeamMember acctMbr = new AccountTeamMember(); 
        acctMbr.AccountId = AccountId;
        acctMbr.TeamMemberRole = TeamMemberRole;    
        acctMbr.userId = UserId;  
      
        System.runAs( UserDataGeneratorHelper_Test.integrationUser ){
            
            Database.insert(acctMbr);
            
        }
        
        return acctMbr;
        
    }
    
    //To create account team member
    public static AccountShare createAccountShare( Id AccountId , Id UserId,  String AcctAccessLevel,  String OpptyAccessLevel, String CaseAccessLevel, String ContactAccessLevel ){
               //system.debug('***AcctAccessLevel***'+AcctAccessLevel); 
        AccountShare acctShare = new AccountShare(); 
        acctShare.AccountId = AccountId;
        acctShare.AccountAccessLevel = AcctAccessLevel; 
        acctShare.OpportunityAccessLevel = OpptyAccessLevel;
        acctShare.CaseAccessLevel = CaseAccessLevel;
        acctShare.ContactAccessLevel = ContactAccessLevel;
        acctShare.UserOrGroupId = UserId;  
      
      System.runAs( UserDataGeneratorHelper_Test.integrationUser ){
            
            Database.insert(acctShare);
            
       }
        
        return acctShare;
        
    }

    
}//EOF of class