force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <description>Show True and False sign depending upon the Account Status.
#RQ-000998 : Formula edited to include condition for Non Shipping account</description>
    <formula>IF(   ISPICKVAL(SCV_Status__c , &apos;Active&apos; ) ||  RecordTypeId ==  $Label.Non_shipping_Party_Account_RecordType_Label  , IMAGE(&quot;/resource/Green_Tick&quot;,&quot;Active&quot;, 13, 13) , IMAGE(&quot;/resource/Red_Cross&quot;,&quot;InActive&quot; , 13, 13) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Displays a visual indicator of whether or not this Account&apos;s Status in SCV. A red cross is &quot;Inactive&quot;, a green tick is &quot;Active&quot;.</inlineHelpText>
    <label>Active</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MCC_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MCC_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0047: 
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.</description>
    <inlineHelpText>The MCC Line sales person responsible for this Account.</inlineHelpText>
    <label>MCC Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MLL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MLL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0054: Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.</description>
    <inlineHelpText>The MLL sales person responsible for this Account.</inlineHelpText>
    <label>MLL Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.MLL__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/MSL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MSL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#Safmarine_United
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.
#RQ-004168 - Updated FLS</description>
    <inlineHelpText>The Maersk Line sales person responsible for this Account.</inlineHelpText>
    <label>Maersk Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_MSL_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#RQ-000235 - Help text added.
#RQ-000608 - Case Management Phase 1 - Removed Lookup filter.</description>
    <inlineHelpText>Primary Sales Contact for Maersk Line.</inlineHelpText>
    <label>z_Maersk Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>SCL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#Safmarine_United
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.
#RQ-004168 - Updated FLS</description>
    <inlineHelpText>The Safmarine sales person responsible for this Account.</inlineHelpText>
    <label>z_Safmarine Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_SCL_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration&quot; .
Unique customer number shared across numerous Maersk systems. Populated by custom Java components in the middleware layer. Should be read-only to users using FLS so there is no chance of modification by anyone other than the Master Data Interface User.
#RQ-002042-Reduced the text characters to 11
#RQ-004927.</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal system identifier from SCV</inlineHelpText>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SEA_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>SEA_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#PR-0031_2 - Sealand Integration. This field is used to store the sealand account Owner</description>
    <inlineHelpText>The SeaLand sales person responsible for this Account.</inlineHelpText>
    <label>Sealand Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_SEA_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brand__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brand__c</fullName>
    <description>#Safmarine_United 
#PR-0047: Added MCC Brand Value to this pick list.
#PR-0055-Added Seago value to the picklist .</description>
    <inlineHelpText>Captures the Brand of the Contact.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brands__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brands__c</fullName>
    <description>#RQ-002893-Captures the Liner Brands of the Contact.</description>
    <inlineHelpText>Captures the Brands of the Contact</inlineHelpText>
    <label>Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004927</description>
    <inlineHelpText>The language in which Customer would like to receive communication.</inlineHelpText>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abkhaz</fullName>
            </value>
            <value>
                <fullName>Afar</fullName>
            </value>
            <value>
                <fullName>Afrikaans</fullName>
            </value>
            <value>
                <fullName>Akan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Amharic</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Aragonese</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Assamese</fullName>
            </value>
            <value>
                <fullName>Avaric</fullName>
            </value>
            <value>
                <fullName>Avestan</fullName>
            </value>
            <value>
                <fullName>Aymara</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bambara</fullName>
            </value>
            <value>
                <fullName>Bashkir</fullName>
            </value>
            <value>
                <fullName>Basque</fullName>
            </value>
            <value>
                <fullName>Belorussian</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Bihari</fullName>
            </value>
            <value>
                <fullName>Bislama</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Breton</fullName>
            </value>
            <value>
                <fullName>Bulgarian</fullName>
            </value>
            <value>
                <fullName>Burmese</fullName>
            </value>
            <value>
                <fullName>Catalan</fullName>
            </value>
            <value>
                <fullName>Chamorro</fullName>
            </value>
            <value>
                <fullName>Chechen</fullName>
            </value>
            <value>
                <fullName>Chichewa, Chewa, Nyanja</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++ Do not change this field without reviewing impact with master data integration. SFMC-7706</description>
    <externalId>true</externalId>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer_Contact.recordType-meta.xml
<RecordType>
    <fullName>Customer_Contact</fullName>
    <active>true</active>
    <description>A person from the customer&apos;s organisation</description>
    <label>Customer Contact</label>
</RecordType>

force-app/main/default/classes/UpdateTaskDueDate_Test.cls
/************************************************************************************************************************************************************************
 * Name        : UpdateTaskDueDateTest 
 * Description: This is a test class created to cover below class :
 *                 1.  UpdateTaskDueDate.trigger 
 *                       
 * --------------------------------------------------------------------------------------------------------------------------------------------------* 
 * Rev       Name                                              Date                        RQ#                       Description                                       
 * 
 * 1.0       Krishnamoorthi.murugesan@ust-global.com           08/12/2014                  #RQ-000828                Removed PPVVC from Opportunity  
 * 2.0       Madhava.kotte@ust-global.com                      11/12/2014                  #PR-00031_2               Named Account functionality for Sealand Opportunities   
 * 3.0       Madhava.kotte@ust-global.com                      12/05/2015                  #PR-0042                  Named Account functionality for MCC opportunities    
 * 4.0       Jiji@UST                                          12/08/2016                  #RQ-004057                Remove reference to Survey_Me__c, Primary_Contact__c field
 * 5.0       manjunath.c.holekade@maersk.com                   06-Jun-2019                 #RQ-010819                Removal of references of deprecated fields 
 * 6.0       manjunath.c.holekade@maersk.com                   12-Nov-2019                 #RQ-012362                Removal of references of deprecated Account fields 
 * 7.0       Meghana@UST						               16-Oct-2020                 #SFSE-4767                Removal of references to Safmarine brand related method 
 * 8.0       Ronnie@SF                                         27-Jun-2022                 SPI-100                   Removed brand hardcoding
 *************************************************************************************************************************************************************************/
@isTest
private class UpdateTaskDueDate_Test {

    public static testMethod void testUpdateTaskDueDateTriggerDualBranded() {
         Test.StartTest();
        List<Opportunity> oppList=new list<Opportunity>();
        List<User> lstuser = new List<User>();
         TriggerExecutionController.skipAllTriggers(true);
        User integrationUser = TestBusinessHelper.createUser('Integration User', BrandUtilities.SEALAND, false);
        integrationUser.ID=null;
      	lstuser.add(integrationUser);
        User MSLintegrationUser = TestBusinessHelper.createUser('Integration User', BrandUtilities.SEAGO, false);
        MSLintegrationUser.ID=null;
        MSLintegrationUser.MLL__c =true;
       	lstuser.add(MSLintegrationUser);
        
		system.runas(new user(id = userinfo.getuserid())){
        
            insert lstuser;
        }
         TriggerExecutionController.skipAllTriggers(false);
        //setup a Account Export_Rep Dual branded
       
        Account acct=new Account();
        
        System.runAs(integrationUser)
        {
            acct.Name='Test Account';
            //acct.MSL_Account_Owner__c=Userinfo.getUserId();
            acct.SCV_Code__c = '2242348789';                 
            acct.MSL_Account_Owner__c= integrationUser.Id;
            acct.MLL_Account_Owner__c= MSLintegrationUser.Id;  
            insert acct;
        }
        
        
        Contact cont= TestBusinessHelper.createContact(acct, 'Customer_Contact', BrandUtilities.MAERSKLINE, true);
        /*cont.LastName  ='testsdf';
        cont.AccountId= acct.id;
        cont.Email='cvghfdg@gmail.play';
        //cont.Primary_Contact__c=true;
        //cont.Survey_Me__c=true; ver4.0
        cont.Liner_Brands__c = BrandUtilities.MAERSKLINE;
        cont.Preferred_Language__c='English';
        insert cont;
        */
        //set up opportunity
        Opportunity opp=TestBusinessHelper.createOpportunity(acct, cont, integrationUser, 'ShippingCargoServices', BrandUtilities.MAERSKLINE, true);
		 /*
        opp.name='testop';
        opp.CloseDate=date.today();
        opp.AccountId=acct.id; 
        opp.StageName= Label.LeadLabel;
        opp.Cargo_Type__c='DRY';
        opp.type='Transactional';
        opp.Primary_contact__c=cont.id;
        opp.Named_Account__c=acct.id;
        opp.Liner_Brand__c = BrandUtilities.MAERSKLINE;
        insert opp; 
        */
        opp = [select id from opportunity where Id=:opp.id];
       
        Task tsk = new Task();
        tsk.Subject='Opportunity Expiration Notification';
        tsk.Status='Not Started';
        tsk.Priority='Normal';
        tsk.WhatID=opp.id;
        tsk.ActivityDate=date.today();
        tsk.ReminderDateTime=date.today(); 
        insert tsk;  
        
        update opp; 
        
        opp = [select id from opportunity where Id=:opp.id];  
        
        Task tsk1 = new Task();
        tsk1.Subject='Opportunity Expiration Notification';
        tsk1.Status='Not Started';
        tsk1.Priority='Normal';
        tsk1.WhatID=opp.id;
        tsk1.ActivityDate=date.today()+1;
        tsk1.ReminderDateTime=date.today()+1; 
        insert tsk1; 
         Test.StopTest(); 
    }
    
    public static testMethod void testUpdateTaskDueDateTriggerSingleBranded() {
        Test.StartTest();
        List<Opportunity> oppList=new list<Opportunity>();
      
        List<User> lstuser = new List<User>();
         TriggerExecutionController.skipAllTriggers(true);
        User integrationUser = TestBusinessHelper.createUser('Integration User', BrandUtilities.SEALAND, false);
        integrationUser.ID=null;
      	lstuser.add(integrationUser);
        User SCLIntegrationUser = TestBusinessHelper.createUser('Integration User', BrandUtilities.SEAGO, false);
        SCLIntegrationUser.ID=null;
        SCLIntegrationUser.MLL__c =true;
       	lstuser.add(SCLIntegrationUser);
        
		system.runas(new user(id = userinfo.getuserid())){
        
            insert lstuser;
        }
        Account acct=new Account();
        
        System.runAs(integrationUser)
        {
            acct.Name='Test Account';
            acct.SCV_Code__c = '2242348789';                 
            acct.MSL_Account_Owner__c= integrationUser.Id;
            //acct.SCL_Account_Owner__c=CreateIntegrationUserData_Test.integrationUser.Id;
            acct.SEA_Account_Owner__c = SCLIntegrationUser.id;
            insert acct;
        }
        Contact cont=  TestBusinessHelper.createContact(acct, 'Customer_Contact', BrandUtilities.MAERSKLINE, true);
        /*cont.LastName  ='testsdf';
        cont.AccountId= acct.id;
        cont.Email='cvghfdg@gmail.play';
        //cont.Primary_Contact__c=true;
        //cont.Survey_Me__c=true; ver4.0
        cont.Liner_Brands__c = BrandUtilities.SEALAND;
        cont.Preferred_Language__c='English';
        System.runAs(CreateIntegrationUserData_Test.integrationUser)
        {
            insert cont;
        }*/
        
        Contact contsl = TestBusinessHelper.createContact(acct, 'Customer_Contact', BrandUtilities.SEALAND, true);
        /*contsl.LastName  ='testsdf';
        contsl.AccountId= acct.id;
        contsl.Email='cvghfdger@gmail.play';
        //contsl.Primary_Contact__c=true;
        //contsl.Survey_Me__c=true; ver4.0
        contsl.Liner_Brands__c = BrandUtilities.SEALAND;
        contsl.Preferred_Language__c='English';
        System.runAs(CreateIntegrationUserData_Test.integrationUser) {
            insert contsl;
        }*/
        
        //set up opportunity
       
        Opportunity oppt;
        //Opp Insertion by single branded MaerskLine user
        system.runAs(SCLIntegrationUser) {
            Validation_Rules_Bypass__c  setting = new Validation_Rules_Bypass__c ();
            setting.Active__c  = true; 
            insert setting;
           oppt=TestBusinessHelper.createOpportunity(acct, cont, SCLIntegrationUser, 'ShippingCargoServices', BrandUtilities.MAERSKLINE, true);
	
            /*oppt.name='testop';
            oppt.CloseDate=date.today()+1;
            oppt.AccountId=acct.id; 
            oppt.StageName= Label.LeadLabel;
            oppt.Cargo_Type__c='DRY';
            oppt.type='Transactional';
            oppt.Primary_contact__c=cont.id;
            oppt.Named_Account__c=acct.id;
            oppt.Liner_Brand__c = BrandUtilities.SEALAND;
            insert oppt;*/
        }
        
        //Opp Insertion by single branded MaerskLine user
        
        Task tsk = new Task();
        tsk.Subject='Opportunity Expiration Notification';
        tsk.Status='Not Started';
        tsk.Priority='Normal';
        tsk.WhatID=oppt.id;
        tsk.ActivityDate=date.today();
        tsk.ReminderDateTime=date.today()+1; 
        insert tsk;  
        
        Opportunity opp = [select id from opportunity where Id=:oppt.id];
        update opp;
        
        opp = [select id from opportunity where Id=:opp.id]; 
        
        
        Task tsk1 = new Task();
        tsk1.Subject='Opportunity Expiration Notification';
        tsk1.Status='Not Started';
        tsk1.Priority='Normal';
        tsk1.WhatID=opp.id;
        tsk1.ActivityDate=date.today()+1;
        tsk1.ReminderDateTime=date.today()+1; 
        insert tsk1;
        Test.StopTest();
    }
    
    /**
*TestDriven Approach: #PR-00031_2 - below test method is for testing the chatter feed for SEA account owner on Sealand opportunity insertion with Named Account
**/
    public static testMethod void sealndOppNamedAccChatterPost() {
        
        Test.StartTest();
        
        UserDataGeneratorHelper_Test.initializeIntegrationUser();
        
        //for inserting the account
        Account lstAcct=new Account();
        system.debug('MSLSystemAdminUser');
        lstAcct.Name='MainAccount';
        lstAcct.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAIntegrationUser.id;
        
        System.runAs(UserDataGeneratorHelper_Test.integrationUser) {
            insert lstAcct;
        }
        
        //for inserting the Named Account
        Account namedAcct=new Account();
        namedAcct.Name='named Acc';
        namedAcct.SEA_Account_Owner__c = UserDataGeneratorHelper_Test.SEAIntegrationUser.id;
        
        System.runAs(UserDataGeneratorHelper_Test.integrationUser) {
            insert namedAcct;
        }
        
        //for inserting the contact
        Contact seaCont=new Contact();
        seaCont.LastName  ='testsdf';
        seaCont.AccountId= lstAcct.id;
        seaCont.Email='cvghfdg@gmail.play';
        //seaCont.Primary_Contact__c=true;
        //seaCont.Survey_Me__c=true;ver4.0
        seaCont.Liner_Brands__c = BrandUtilities.SEALAND;
        seaCont.Preferred_Language__c='English';
        System.runAs(UserDataGeneratorHelper_Test.SEAIntegrationUser) {
            insert seaCont;
        }
        
        //for inserting the opportunity
        Opportunity namedOpp = new Opportunity();
        namedOpp.name = 'testop123';
        namedOpp.CloseDate = date.today();
        namedOpp.AccountId = lstAcct.id; 
        namedOpp.StageName =  Label.LeadLabel;
        namedOpp.Cargo_Type__c = 'DRY';
        namedOpp.type = 'Transactional';
        namedOpp.Primary_contact__c = seaCont.id;
        namedOpp.Named_Account__c = namedAcct.id;
        namedOpp.Liner_Brand__c = BrandUtilities.SEALAND;
        namedOpp.Expected_Handling_Rounds__c=2;
        System.runAs(UserDataGeneratorHelper_Test.SEAIntegrationUser) {
            insert namedOpp;
        }
        Test.StopTest();
    }
    
    
    /**
    *TestDriven Approach: #PR-0042 - below test method is for testing the chatter feed for MCC account owner on MCC opportunity insertion with Named Account
    **/
    public static testMethod void mccOppNamedAccChatterPost() {
        
        Test.StartTest();
        
        UserDataGeneratorHelper_Test.initializeIntegrationUser();
        
        //for inserting the account
        Account lstAcct=new Account();
        lstAcct.Name='MainAccount';
        lstAcct.MCC_Account_Owner__c = UserDataGeneratorHelper_Test.MCCIntegrationUser.id;
        
        System.runAs(UserDataGeneratorHelper_Test.integrationUser) {
            insert lstAcct;
        }
        
        //for inserting the Named Account
        Account namedAcct=new Account();
        namedAcct.Name='named Acc';
        namedAcct.MCC_Account_Owner__c = UserDataGeneratorHelper_Test.MCCIntegrationUser.id;
        
        System.runAs(UserDataGeneratorHelper_Test.integrationUser) {
            insert namedAcct;
        }
        
        //for inserting the contact
        Contact mccCont=new Contact();
        mccCont.LastName  ='testsdf';
        mccCont.AccountId= lstAcct.id;
        mccCont.Email='cvghfdg@gmail.play';
        //mccCont.Primary_Contact__c=true;
        //mccCont.Survey_Me__c=true;ver4.0
        mccCont.Liner_Brands__c = BrandUtilities.MCC;
        mccCont.Preferred_Language__c='English';
        System.runAs(UserDataGeneratorHelper_Test.MCCIntegrationUser) {
            insert mccCont;
        }
        
        //for inserting the opportunity
        Opportunity opp = new Opportunity();
        opp.name = 'testop123';
        opp.CloseDate = date.today();
        opp.AccountId = lstAcct.id; 
        opp.StageName =  Label.LeadLabel;
        opp.Cargo_Type__c = 'DRY';
        opp.type = 'Transactional';
        opp.Primary_contact__c = mccCont.id;
        opp.Liner_Brand__c = BrandUtilities.MCC;
        opp.Expected_Handling_Rounds__c=2;
        System.runAs(UserDataGeneratorHelper_Test.MCCIntegrationUser) {
            insert Opp;
            List<OpportunityFeed> oppFeedLst = [select id, ParentId From OpportunityFeed where parentId=:opp.id];
            system.assertEquals(oppFeedLst.size()>0,false);
        }
        
        //for inserting the opportunity for Named Account
        Opportunity namedOpp = new Opportunity();
        namedOpp.name = 'testop123';
        namedOpp.CloseDate = date.today();
        namedOpp.AccountId = lstAcct.id; 
        namedOpp.StageName =  Label.LeadLabel;
        namedOpp.Cargo_Type__c = 'DRY';
        namedOpp.type = 'Transactional';
        namedOpp.Primary_contact__c = mccCont.id;
        namedOpp.Named_Account__c = namedAcct.id;
        namedOpp.Liner_Brand__c = BrandUtilities.MCC;
        namedOpp.Expected_Handling_Rounds__c=2;
        
        System.runAs(UserDataGeneratorHelper_Test.MCCIntegrationUser) {
            insert namedOpp;
        }
        Test.StopTest();
    }
}