force-app/main/default/objects/Account/fields/Attractiveness__c.field-meta.xml
<CustomField>
    <fullName>Attractiveness__c</fullName>
    <label>Attractiveness</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Booster</fullName>
            </value>
            <value>
                <fullName>Runway</fullName>
            </value>
            <value>
                <fullName>A-MCC</fullName>
                <isActive>false</isActive>
                <label>A-MCC</label>
            </value>
            <value>
                <fullName>A-MLL</fullName>
                <isActive>false</isActive>
                <label>A-MLL</label>
            </value>
            <value>
                <fullName>A-SCL</fullName>
                <isActive>false</isActive>
                <label>A-SCL</label>
            </value>
            <value>
                <fullName>A-SEA</fullName>
                <isActive>false</isActive>
                <label>A-SEA</label>
            </value>
            <value>
                <fullName>A-SGO</fullName>
                <isActive>false</isActive>
                <label>A-SGO</label>
            </value>
            <value>
                <fullName>B-MCC</fullName>
                <isActive>false</isActive>
                <label>B-MCC</label>
            </value>
            <value>
                <fullName>B-MLL</fullName>
                <isActive>false</isActive>
                <label>B-MLL</label>
            </value>
            <value>
                <fullName>B-MSL</fullName>
                <isActive>false</isActive>
                <label>B-MSL</label>
            </value>
            <value>
                <fullName>B-SCL</fullName>
                <isActive>false</isActive>
                <label>B-SCL</label>
            </value>
            <value>
                <fullName>B-SEA</fullName>
                <isActive>false</isActive>
                <label>B-SEA</label>
            </value>
            <value>
                <fullName>B-SGO</fullName>
                <isActive>false</isActive>
                <label>B-SGO</label>
            </value>
            <value>
                <fullName>Booster-MSL</fullName>
                <isActive>false</isActive>
                <label>Booster-MSL</label>
            </value>
            <value>
                <fullName>C-MCC</fullName>
                <isActive>false</isActive>
                <label>C-MCC</label>
            </value>
            <value>
                <fullName>C-MLL</fullName>
                <isActive>false</isActive>
                <label>C-MLL</label>
            </value>
            <value>
                <fullName>C-MSL</fullName>
                <isActive>false</isActive>
                <label>C-MSL</label>
            </value>
            <value>
                <fullName>C-SCL</fullName>
                <isActive>false</isActive>
                <label>C-SCL</label>
            </value>
            <value>
                <fullName>C-SEA</fullName>
                <isActive>false</isActive>
                <label>C-SEA</label>
            </value>
            <value>
                <fullName>C-SGO</fullName>
                <isActive>false</isActive>
                <label>C-SGO</label>
            </value>
            <value>
                <fullName>Efficiency Key Client-MSL</fullName>
                <isActive>false</isActive>
                <label>Efficiency Key Client-MSL</label>
            </value>
            <value>
                <fullName>Extended Runway-MSL</fullName>
                <isActive>false</isActive>
                <label>Extended Runway-MSL</label>
            </value>
            <value>
                <fullName>Key - Client</fullName>
                <isActive>false</isActive>
                <label>Key - Client</label>
            </value>
            <value>
                <fullName>Key Client-MCC</fullName>
                <isActive>false</isActive>
                <label>Key Client-MCC</label>
            </value>
            <value>
                <fullName>Key Client-MLL</fullName>
                <isActive>false</isActive>
                <label>Key Client-MLL</label>
            </value>
            <value>
                <fullName>Key Client-MSL</fullName>
                <isActive>false</isActive>
                <label>Key Client-MSL</label>
            </value>
            <value>
                <fullName>Key Client-SCL</fullName>
                <isActive>false</isActive>
                <label>Key Client-SCL</label>
            </value>
            <value>
                <fullName>Key Client-SEA</fullName>
                <isActive>false</isActive>
                <label>Key Client-SEA</label>
            </value>
            <value>
                <fullName>Key Client-SGO</fullName>
                <isActive>false</isActive>
                <label>Key Client-SGO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Size__c.field-meta.xml
<CustomField>
    <fullName>Customer_Size__c</fullName>
    <description>+++ INTEGRATION: Maestro DATA +++
Do not change this field without reviewing impact with Maestro data integration.</description>
    <inlineHelpText>Customer size is estimated based on the total addressable logistics spend (for ocean &amp; L&amp;S products with all providers).</inlineHelpText>
    <label>Customer Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
This field is added for selecting industries on account.
#RQ-000235 - Added picklist value &quot;Other&quot; and Help text.
#RQ-004927
#RQ-004162 - Removed the picklist value &quot;other&quot;</description>
    <inlineHelpText>Indicates the industry categories this account is involved with</inlineHelpText>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture Horticulture &amp; Livestock</fullName>
            </value>
            <value>
                <fullName>Banking Insurance &amp; Financial Services</fullName>
            </value>
            <value>
                <fullName>Biotechnology and Life Sciences</fullName>
            </value>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Chemicals Petroleum Rubber &amp; Plastic</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Computer Hardware</fullName>
            </value>
            <value>
                <fullName>Computer Software</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Food &amp; Tobacco Manufacturing</fullName>
            </value>
            <value>
                <fullName>Industrial Electric &amp; Electronic Machinery</fullName>
            </value>
            <value>
                <fullName>Information Services</fullName>
            </value>
            <value>
                <fullName>Leather Stone Clay &amp; Glass Products</fullName>
            </value>
            <value>
                <fullName>Media &amp; Broadcasting</fullName>
            </value>
            <value>
                <fullName>Metals &amp; Metal Products</fullName>
            </value>
            <value>
                <fullName>Mining &amp; Extraction</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Manufacturing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Printing &amp; Publishing</fullName>
            </value>
            <value>
                <fullName>Property Services</fullName>
            </value>
            <value>
                <fullName>Public Administration Education Health Social Services</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Textiles &amp; Clothing Manufacturing</fullName>
            </value>
            <value>
                <fullName>Transport Freight and Storage</fullName>
            </value>
            <value>
                <fullName>Transport Manufacturing</fullName>
            </value>
            <value>
                <fullName>Travel Personal &amp; Leisure</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
            <value>
                <fullName>Waste Management &amp; Treatment</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Wood Furniture &amp; Paper Manufacturing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Represents_Concern__c.field-meta.xml
<CustomField>
    <fullName>Represents_Concern__c</fullName>
    <defaultValue>false</defaultValue>
    <description>#RQ-004705
As part of the interim solution will create a new field called &quot;Represents Concern&quot; and this is to show the equivalent of the &quot;Is-Concern&quot; relationship that master data will have</description>
    <inlineHelpText>When set to true this highlights that this SCV code is the equivalent of the concern level account</inlineHelpText>
    <label>Represents Concern</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <description>SFSE-10947: This field is used to classify our customers so that Sales can target them with the right offering. It is updated from external data sources.</description>
    <inlineHelpText>Sales Channel refers to our new sales organization setup and considers how we interact with the account: Key Client/Runway, Integrated Sales, or Direct Transport Sales</inlineHelpText>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration&quot; .
Unique customer number shared across numerous Maersk systems. Populated by custom Java components in the middleware layer. Should be read-only to users using FLS so there is no chance of modification by anyone other than the Master Data Interface User.
#RQ-002042-Reduced the text characters to 11
#RQ-004927.</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal system identifier from SCV</inlineHelpText>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Status__c.field-meta.xml
<CustomField>
    <fullName>SCV_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot;
#RQ-000235 - Help text added.
#RQ-004162 - Changed Field label and help text
#RQ-004927.</description>
    <inlineHelpText>Indicates if this customer is active or not as per Customer Master Data definitions</inlineHelpText>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sub_Segment__c</fullName>
    <description>RQ-009401</description>
    <inlineHelpText>Indicates the sub-segment within the Efficiency Value Proposition</inlineHelpText>
    <label>Sub Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small Medium Forwarder</fullName>
            </value>
            <value>
                <fullName>Local Champion</fullName>
            </value>
            <value>
                <fullName>Global Freight Forwarder</fullName>
            </value>
            <value>
                <fullName>Specialised Forwarder</fullName>
            </value>
            <value>
                <fullName>Digital Innovator</fullName>
            </value>
            <value>
                <fullName>BIG BCO specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sync_to_SFMC__c.field-meta.xml
<CustomField>
    <fullName>Sync_to_SFMC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>RQ-013401 : Marketing Cloud Account/Contact Sync flag</description>
    <label>Sync to SFMC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Value_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Value_Proposition__c</fullName>
    <description>+++ INTEGRATION: SFMC +++
Do not change this field without reviewing impact with Marketing cloud&quot; .
Existing contact report that feeds SFMC may need to be changed</description>
    <label>Value Proposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Value_Proposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration</description>
    <inlineHelpText>Sales vertical that the account is assigned to in Maersk</inlineHelpText>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Vertical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Client Accounts are customers who place bookings with the company and WILL have an SCV code. Client Accounts are mastered in SCV.</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Concern_Account.recordType-meta.xml
<RecordType>
    <fullName>Concern_Account</fullName>
    <active>true</active>
    <description>Concern Accounts are the Parents of Clients customers who place bookings with the company and WILL have an SCV code (begining with ***). Concerns are mastered in SCV.</description>
    <label>Concern Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Draft_Account.recordType-meta.xml
<RecordType>
    <fullName>Draft_Account</fullName>
    <active>true</active>
    <description>Draft Accounts are new customers who have never done business with the company and so do not have an SCV code but need Quotes issued to them.</description>
    <label>Draft Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++ Do not change this field without reviewing impact with master data integration. SFMC-7706</description>
    <externalId>true</externalId>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer_Contact.recordType-meta.xml
<RecordType>
    <fullName>Customer_Contact</fullName>
    <active>true</active>
    <description>A person from the customer&apos;s organisation</description>
    <label>Customer Contact</label>
</RecordType>

force-app/main/default/classes/AccountHierarchyManager_Test.cls
/*              
* Revision Ref Number  Date        Owner                           Description
* -------- ----------  ----------- -------------------             -----------
* 1.0      RQ-005390   05-Jun-2017 Nisha@ust                     Test Class for AccountHierarchyManager
* 2.0      SFSE-14450  26-Mar-2024 Aleena@maersk                 Added for customer size
*/

@isTest
public class AccountHierarchyManager_Test {   
    @testSetup static void setup() {
        List<Account> lstConcernAccount = TestBusinessHelper.createAccounts(new List<String>{'Concern_Account','Concern_Account' },false);
        lstConcernAccount[0].Id = null;
        lstConcernAccount[0].Name = 'Test Conern 1';
        lstConcernAccount[0].SCV_Code__c = 'TestABC';

        lstConcernAccount[1].Id = null;
        lstConcernAccount[1].Name = 'Test Conern 1';
        lstConcernAccount[1].SCV_Code__c = 'TestXYZ';

        insert lstConcernAccount;
        List<Account> lstClientAccount = TestBusinessHelper.createAccounts(new List<String>{'Client_Account','Client_Account' },false);
        lstClientAccount[0].Id = null;
        lstClientAccount[0].Name = 'Test Client 1';
        lstClientAccount[0].SCV_Code__c = 'TestDEF';

        lstClientAccount[1].Id = null;
        lstClientAccount[1].Name = 'Test Client 1';
        lstClientAccount[1].SCV_Code__c = 'Test123';

        insert lstClientAccount;
    }
    /*public static testMethod void test_updateRepresentsConcern(){
        
       AccountData_Test.iNumberOfAccounts = 1;
       AccountData_Test.createConcernAccounts();
        list<Account> lstConcernAccounts = new list<Account>();  
        lstConcernAccounts =AccountData_Test.lstAccounts;
        
       AccountData_Test.iNumberOfAccounts = 2;
       AccountData_Test.createClientAccounts();
        list<Account> lstClientAccounts = new list<Account>();    
        lstClientAccounts =AccountData_Test.lstAccounts;
        
        for(Account accIterator : lstClientAccounts) {
            accIterator.ParentId = lstConcernAccounts[0].Id;
            accIterator.Represents_Concern__c  = TRUE;
        }   
        update lstClientAccounts[0];
        
        for(Account accIterator : lstClientAccounts) {
            accIterator.ParentId = lstConcernAccounts[0].Id; 
            accIterator.Represents_Concern__c  = FALSE;
        } 
        update lstClientAccounts[1];
        
        for(Account accIterator : lstClientAccounts) {         
            accIterator.Represents_Concern__c  = TRUE;
        }
        
        Test.startTest();   
        update lstClientAccounts[1];
        Test.stopTest();
        
        list<Account> lstRepresentConcernUpdated = new list<Account>([SELECT Id, Represents_Concern__c FROM Account WHERE Id =: lstClientAccounts[0].Id]);
        System.assertEquals(lstRepresentConcernUpdated[0].Represents_Concern__c,FALSE);                   
    }
    */
    static testmethod void  voidtest_updateConcern(){
        Test.startTest();
        List<Account> lstConcernAccount = [SELECT id FROM Account WHERE Recordtype.name = 'Concern Account'];
        List<Account> lstClientAccount = [SELECT id,ParentId,Represents_Concern__c FROM Account WHERE Recordtype.name = 'Client Account'];
         
        lstClientAccount[0].ParentId = lstConcernAccount[0].Id;
        lstClientAccount[0].Represents_Concern__c = true;
         
        lstClientAccount[1].ParentId = lstConcernAccount[0].Id;
        lstClientAccount[1].Represents_Concern__c = true;
        
        update lstClientAccount;

        Account clientAccount = TestBusinessHelper.createAccount('Client_Account', false);
        clientAccount.Id = null;
        clientAccount.ParentId = lstConcernAccount[0].Id;
        clientAccount.Represents_Concern__c = true;

        insert clientAccount;

        
        lstClientAccount[0].ParentId = lstConcernAccount[0].Id;

        update lstClientAccount;

        lstClientAccount[0].ParentId = lstConcernAccount[1].Id;
        lstClientAccount[0].Represents_Concern__c = false;

        update lstClientAccount[0];

        
        Test.stopTest();
    }

    static testmethod void  voidtest_updateConernTrue(){
        Test.startTest();
        List<Account> lstConcernAccount = [SELECT id FROM Account WHERE Recordtype.name = 'Concern Account'];
        
        TriggerExecutionController.skipAllTriggers(true);
        Account clientAccount = TestBusinessHelper.createAccount('Client_Account', false);
        clientAccount.Id = null;
        //clientAccount.ParentId = lstConcernAccount[0].Id;
        clientAccount.Represents_Concern__c = true;
        insert clientAccount;
        TriggerExecutionController.skipAllTriggers(false);
       
        clientAccount.ParentId = lstConcernAccount[0].Id;
        clientAccount.Represents_Concern__c = true;
        update clientAccount;
        
        Test.stopTest();
    }

    static testmethod void  voidtest_keyAttributesChanegs(){
        Test.startTest();
        List<Account> lstConcernAccount = [SELECT id FROM Account WHERE Recordtype.name = 'Concern Account'];
        List<Account> lstClientAccount = [SELECT id,ParentId,Represents_Concern__c FROM Account WHERE Recordtype.name = 'Client Account'];
         
        lstClientAccount[0].ParentId = lstConcernAccount[0].Id;
        lstClientAccount[0].Represents_Concern__c = true;
        lstClientAccount[0].Attractiveness__c = 'Runway';
        lstClientAccount[0].Vertical__c = 'Automotive';
        lstClientAccount[0].Industry__c = 'Banking Insurance & Financial Services';
        lstClientAccount[0].Value_Proposition__c = 'Efficiency';
        lstClientAccount[0].Sub_Segment__c = 'Local Champion';
        lstClientAccount[0].Sales_Channel__c = 'Integrated Sales';
        lstClientAccount[0].Customer_Size__c = 'Large'; 
        
        update lstClientAccount[0];

        Account clientAccount = TestBusinessHelper.createAccount('Client_Account', false);
        clientAccount.Id = null;
        clientAccount.ParentId = lstConcernAccount[0].Id;
        clientAccount.Represents_Concern__c = true;
        clientAccount.Attractiveness__c = 'Key Client';
        clientAccount.Vertical__c =  'Lifestyle';
        clientAccount.Industry__c = 'Business Services';
        clientAccount.Value_Proposition__c = 'Ambition';
        clientAccount.Sub_Segment__c = 'Digital Innovator';
        clientAccount.Sales_Channel__c = 'Key Client/Runway';
        clientAccount.Customer_Size__c = 'Large';
        insert clientAccount;

        lstClientAccount[0].ParentId = lstConcernAccount[1].Id;
        lstClientAccount[0].Represents_Concern__c = true;

        update lstClientAccount[0];
        Test.stopTest();
    }

    static testmethod void  voidtest_updateContact(){
        Test.startTest();
        Id clientRecordTypeId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Client Account').getRecordTypeId();

        List<Account> lstConcernAccount = [SELECT id FROM Account WHERE Recordtype.name = 'Concern Account'];
        List<Account> lstClientAccount = [SELECT id,ParentId,Represents_Concern__c FROM Account WHERE Recordtype.name = 'Client Account'];
         
        
        Account clientAccount = TestBusinessHelper.createAccount('Draft_Account', true);

        

        Contact customerContactMaersk = TestBusinessHelper.createContact(clientAccount, 'Customer_Contact', BrandUtilities.MAERSKLINE, false);
        customerContactMaersk.Id = null;
        customerContactMaersk.LastName = 'CustomerContactMaersk';
        customerContactMaersk.Phone = '+44 123456';
        customerContactMaersk.MobilePhone = '+44 123456';
        customerContactMaersk.OtherPhone = '+44 123456';
        customerContactMaersk.Fax = '+44 123456';
        insert customerContactMaersk;

        clientAccount.recordtypeId=clientRecordTypeId;
        clientAccount.ParentId = lstConcernAccount[0].Id;
        clientAccount.Represents_Concern__c = true;
        clientAccount.Attractiveness__c = 'Key Client';
        clientAccount.Vertical__c =  'Lifestyle';
        clientAccount.Industry__c = 'Business Services';
        clientAccount.Value_Proposition__c = 'Ambition';
        clientAccount.Sub_Segment__c = 'Digital Innovator';
        clientAccount.Sales_Channel__c = 'Key Client/Runway';
        clientAccount.Customer_Size__c = 'Large';
        update clientAccount;
        

        
        Test.stopTest();
    }
	
    static testmethod void  voidtest_setSFMCFlagUpdate(){
        Test.startTest();
        Id clientRecordTypeId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Client Account').getRecordTypeId();

        List<Account> lstConcernAccount = [SELECT id FROM Account WHERE Recordtype.name = 'Concern Account'];
        List<Account> lstClientAccount = [SELECT id,ParentId,Represents_Concern__c FROM Account WHERE Recordtype.name = 'Client Account'];
         
        lstClientAccount[0].SCV_Status__c ='Inactive';
        lstClientAccount[0].Sync_to_SFMC__c = true;
        lstClientAccount[0].SCV_Status__c = 'Inactive';

        update lstClientAccount;

        Account clientAccount = TestBusinessHelper.createAccount('Draft_Account', true);

        clientAccount.SCV_Status__c = 'Active';
        clientAccount.Sync_to_SFMC__c = false;
    

        update clientAccount;
        

        
        Test.stopTest();
    }

    static testmethod void  voidtest_setSFMCFlagInsert(){
        Test.startTest();
        

        List<Account> lstClientAccount = TestBusinessHelper.createAccounts(new List<String>{'Client_Account','Client_Account' ,'Client_Account'},false);
        lstClientAccount[0].Id = null;
        lstClientAccount[0].Name = 'Test Client abc';
        lstClientAccount[0].SCV_Code__c = 'Test980';
        lstClientAccount[0].SCV_Status__c ='Inactive';

        lstClientAccount[1].Id = null;
        lstClientAccount[1].Name = 'Test Client def';
        lstClientAccount[1].SCV_Code__c = 'Test314';
        lstClientAccount[1].Sync_to_SFMC__c = true;
        lstClientAccount[1].SCV_Status__c = 'Inactive';

        lstClientAccount[2].Id = null;
        lstClientAccount[2].Name = 'Test Client ghj';
        lstClientAccount[2].SCV_Code__c = 'Test456';
        lstClientAccount[2].Sync_to_SFMC__c = false;
        lstClientAccount[2].SCV_Status__c = 'Active';

        insert lstClientAccount;

        
        Test.stopTest();
    }

    static testmethod void voidtest_changeOwner(){
        test.startTest();
        TriggerExecutionController.skipAllTriggers(true);
        User maerskUser = TestBusinessHelper.createUser('Sales', BrandUtilities.MAERSKLINE + ';' + BrandUtilities.MAERSKLS, false);
        User mlluser = TestBusinessHelper.createUser('Sales', BrandUtilities.MAERSKLINE + ';' + BrandUtilities.MAERSKLS, false);
        User sealandUser = TestBusinessHelper.createUser('Sales', BrandUtilities.SEALAND, false);
        User seagoUser = TestBusinessHelper.createUser('Sales', BrandUtilities.SEAGO, false);
        maerskUser.Id = null;
        sealandUser.id = null;
        seagoUser.Id = null;
        mlluser.Id = null;
        mlluser.MLL__c= true;
        System.runAs(new User(Id = UserInfo.getUserId())){
            insert new List<User>{maerskUser, sealandUser, seagoUser,mlluser};
        }

        List<Account> lstClientAccount = [SELECT id,ParentId,Represents_Concern__c FROM Account WHERE Recordtype.name = 'Client Account'];
        lstClientAccount[0].MSL_Account_Owner__c = maerskUser.Id;
        lstClientAccount[0].SEA_Account_Owner__c = sealandUser.Id;
        lstClientAccount[0].Seago_Account_Owner__c = maerskUser.Id;
        lstClientAccount[0].MCC_Account_Owner__c = seagoUser.Id;
    
        update lstClientAccount[0];

        TriggerExecutionController.skipAllTriggers(false);
        

        lstClientAccount[0].MSL_Account_Owner__c = sealandUser.Id;
        lstClientAccount[0].SEA_Account_Owner__c = maerskUser.Id;
        lstClientAccount[0].MLL_Account_Owner__c = mlluser.Id;
        lstClientAccount[0].Seago_Account_Owner__c = seagoUser.Id;
        lstClientAccount[0].MCC_Account_Owner__c = sealandUser.Id;
        update lstClientAccount[0];
        test.stopTest();
    }
    
}