force-app/main/default/objects/Account/fields/Attractiveness__c.field-meta.xml
<CustomField>
    <fullName>Attractiveness__c</fullName>
    <label>Attractiveness</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Key Client</fullName>
            </value>
            <value>
                <fullName>Booster</fullName>
            </value>
            <value>
                <fullName>Runway</fullName>
            </value>
            <value>
                <fullName>A-MCC</fullName>
                <isActive>false</isActive>
                <label>A-MCC</label>
            </value>
            <value>
                <fullName>A-MLL</fullName>
                <isActive>false</isActive>
                <label>A-MLL</label>
            </value>
            <value>
                <fullName>A-SCL</fullName>
                <isActive>false</isActive>
                <label>A-SCL</label>
            </value>
            <value>
                <fullName>A-SEA</fullName>
                <isActive>false</isActive>
                <label>A-SEA</label>
            </value>
            <value>
                <fullName>A-SGO</fullName>
                <isActive>false</isActive>
                <label>A-SGO</label>
            </value>
            <value>
                <fullName>B-MCC</fullName>
                <isActive>false</isActive>
                <label>B-MCC</label>
            </value>
            <value>
                <fullName>B-MLL</fullName>
                <isActive>false</isActive>
                <label>B-MLL</label>
            </value>
            <value>
                <fullName>B-MSL</fullName>
                <isActive>false</isActive>
                <label>B-MSL</label>
            </value>
            <value>
                <fullName>B-SCL</fullName>
                <isActive>false</isActive>
                <label>B-SCL</label>
            </value>
            <value>
                <fullName>B-SEA</fullName>
                <isActive>false</isActive>
                <label>B-SEA</label>
            </value>
            <value>
                <fullName>B-SGO</fullName>
                <isActive>false</isActive>
                <label>B-SGO</label>
            </value>
            <value>
                <fullName>Booster-MSL</fullName>
                <isActive>false</isActive>
                <label>Booster-MSL</label>
            </value>
            <value>
                <fullName>C-MCC</fullName>
                <isActive>false</isActive>
                <label>C-MCC</label>
            </value>
            <value>
                <fullName>C-MLL</fullName>
                <isActive>false</isActive>
                <label>C-MLL</label>
            </value>
            <value>
                <fullName>C-MSL</fullName>
                <isActive>false</isActive>
                <label>C-MSL</label>
            </value>
            <value>
                <fullName>C-SCL</fullName>
                <isActive>false</isActive>
                <label>C-SCL</label>
            </value>
            <value>
                <fullName>C-SEA</fullName>
                <isActive>false</isActive>
                <label>C-SEA</label>
            </value>
            <value>
                <fullName>C-SGO</fullName>
                <isActive>false</isActive>
                <label>C-SGO</label>
            </value>
            <value>
                <fullName>Efficiency Key Client-MSL</fullName>
                <isActive>false</isActive>
                <label>Efficiency Key Client-MSL</label>
            </value>
            <value>
                <fullName>Extended Runway-MSL</fullName>
                <isActive>false</isActive>
                <label>Extended Runway-MSL</label>
            </value>
            <value>
                <fullName>Key - Client</fullName>
                <isActive>false</isActive>
                <label>Key - Client</label>
            </value>
            <value>
                <fullName>Key Client-MCC</fullName>
                <isActive>false</isActive>
                <label>Key Client-MCC</label>
            </value>
            <value>
                <fullName>Key Client-MLL</fullName>
                <isActive>false</isActive>
                <label>Key Client-MLL</label>
            </value>
            <value>
                <fullName>Key Client-MSL</fullName>
                <isActive>false</isActive>
                <label>Key Client-MSL</label>
            </value>
            <value>
                <fullName>Key Client-SCL</fullName>
                <isActive>false</isActive>
                <label>Key Client-SCL</label>
            </value>
            <value>
                <fullName>Key Client-SEA</fullName>
                <isActive>false</isActive>
                <label>Key Client-SEA</label>
            </value>
            <value>
                <fullName>Key Client-SGO</fullName>
                <isActive>false</isActive>
                <label>Key Client-SGO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Customer_Size__c.field-meta.xml
<CustomField>
    <fullName>Customer_Size__c</fullName>
    <description>+++ INTEGRATION: Maestro DATA +++
Do not change this field without reviewing impact with Maestro data integration.</description>
    <inlineHelpText>Customer size is estimated based on the total addressable logistics spend (for ocean &amp; L&amp;S products with all providers).</inlineHelpText>
    <label>Customer Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
This field is added for selecting industries on account.
#RQ-000235 - Added picklist value &quot;Other&quot; and Help text.
#RQ-004927
#RQ-004162 - Removed the picklist value &quot;other&quot;</description>
    <inlineHelpText>Indicates the industry categories this account is involved with</inlineHelpText>
    <label>Industry</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture Horticulture &amp; Livestock</fullName>
            </value>
            <value>
                <fullName>Banking Insurance &amp; Financial Services</fullName>
            </value>
            <value>
                <fullName>Biotechnology and Life Sciences</fullName>
            </value>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Chemicals Petroleum Rubber &amp; Plastic</fullName>
            </value>
            <value>
                <fullName>Communications</fullName>
            </value>
            <value>
                <fullName>Computer Hardware</fullName>
            </value>
            <value>
                <fullName>Computer Software</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Food &amp; Tobacco Manufacturing</fullName>
            </value>
            <value>
                <fullName>Industrial Electric &amp; Electronic Machinery</fullName>
            </value>
            <value>
                <fullName>Information Services</fullName>
            </value>
            <value>
                <fullName>Leather Stone Clay &amp; Glass Products</fullName>
            </value>
            <value>
                <fullName>Media &amp; Broadcasting</fullName>
            </value>
            <value>
                <fullName>Metals &amp; Metal Products</fullName>
            </value>
            <value>
                <fullName>Mining &amp; Extraction</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Manufacturing</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Printing &amp; Publishing</fullName>
            </value>
            <value>
                <fullName>Property Services</fullName>
            </value>
            <value>
                <fullName>Public Administration Education Health Social Services</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Textiles &amp; Clothing Manufacturing</fullName>
            </value>
            <value>
                <fullName>Transport Freight and Storage</fullName>
            </value>
            <value>
                <fullName>Transport Manufacturing</fullName>
            </value>
            <value>
                <fullName>Travel Personal &amp; Leisure</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
            <value>
                <fullName>Waste Management &amp; Treatment</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Wood Furniture &amp; Paper Manufacturing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Represents_Concern__c.field-meta.xml
<CustomField>
    <fullName>Represents_Concern__c</fullName>
    <defaultValue>false</defaultValue>
    <description>#RQ-004705
As part of the interim solution will create a new field called &quot;Represents Concern&quot; and this is to show the equivalent of the &quot;Is-Concern&quot; relationship that master data will have</description>
    <inlineHelpText>When set to true this highlights that this SCV code is the equivalent of the concern level account</inlineHelpText>
    <label>Represents Concern</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Channel__c.field-meta.xml
<CustomField>
    <fullName>Sales_Channel__c</fullName>
    <description>SFSE-10947: This field is used to classify our customers so that Sales can target them with the right offering. It is updated from external data sources.</description>
    <inlineHelpText>Sales Channel refers to our new sales organization setup and considers how we interact with the account: Key Client/Runway, Integrated Sales, or Direct Transport Sales</inlineHelpText>
    <label>Sales Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Channel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Segment__c.field-meta.xml
<CustomField>
    <fullName>Sub_Segment__c</fullName>
    <description>RQ-009401</description>
    <inlineHelpText>Indicates the sub-segment within the Efficiency Value Proposition</inlineHelpText>
    <label>Sub Segment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Small Medium Forwarder</fullName>
            </value>
            <value>
                <fullName>Local Champion</fullName>
            </value>
            <value>
                <fullName>Global Freight Forwarder</fullName>
            </value>
            <value>
                <fullName>Specialised Forwarder</fullName>
            </value>
            <value>
                <fullName>Digital Innovator</fullName>
            </value>
            <value>
                <fullName>BIG BCO specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Value_Proposition__c.field-meta.xml
<CustomField>
    <fullName>Value_Proposition__c</fullName>
    <description>+++ INTEGRATION: SFMC +++
Do not change this field without reviewing impact with Marketing cloud&quot; .
Existing contact report that feeds SFMC may need to be changed</description>
    <label>Value Proposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Value_Proposition</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Vertical__c.field-meta.xml
<CustomField>
    <fullName>Vertical__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration</description>
    <inlineHelpText>Sales vertical that the account is assigned to in Maersk</inlineHelpText>
    <label>Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Account_Vertical</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountHierarchyManager.cls
/*
* Author   : Nisha
* Purpose  : Update 'Represents Concern' on client account 
*        
* Revision Ref Number   Date            Owner                           Description
* -------- ----------   -----------     -------------------     		-----------
* 1.0      RQ-005390    05-Jun-2017     Nisha@UST                       Created. 
* 1.0      RQ-010288    29-May-2019     Junaid.Khader@ust-global.com    Defect fix. Commented the line which blanks out the parentId of the client account.
* 2.0      SFSE-7624    05-Jan-2022     Kiran@Maersk				    Live issue fix. Attractiveness field null checks added in updateAccountPlanKCAccount method
* 3.0      SFSE-14282   23-Feb-2023     Samar@Maersk                    Moving Account Process Builder to Trigger.
*/

public class AccountHierarchyManager {
    
    /*@future
    public static void updateAccountPlanKCAccount(Set<Id> accIds){
        List<Business_Plan__c> lstBSPtoUpdate = new List<Business_Plan__c>();
         map<Id, Account> mapAccounts = new map<Id, Account>([SELECT Id, Attractiveness__c FROM Account 
                                                              WHERE Id IN :accIds]);
        List<Business_Plan__c> lstGetAccountPlan = [SELECT Id, Lead_Account__c, Key_Client_Account__c FROM Business_Plan__c
                                                   WHERE Lead_Account__c IN: accIds];
        for(Business_Plan__c bsp: lstGetAccountPlan) {
            Account accIterator = mapAccounts.get(bsp.Lead_Account__c);
            if(String.isNotEmpty(accIterator.Attractiveness__c) && (accIterator.Attractiveness__c.contains('Key Client') || accIterator.Attractiveness__c.contains('Runway') || accIterator.Attractiveness__c.contains('Efficiency'))) {
              bsp.Key_Client_Account__c = 'Yes';  
            } else{
               bsp.Key_Client_Account__c = 'No'; 
            }
            lstBSPtoUpdate.add(bsp);
        }
            asklas
            asmdsa
            asdlkas;
        
        try{
            update lstBSPtoUpdate;
        }catch(Exception e) {
            
        }
    }*/
    
    public static void updateRepresentsConcern(set<Id> setConcernIds, set<Id> setExcludedClientIds) {
        try {
                //Generic_TriggerHandler.validateRunForMethod SS1
    //Generic_TriggerHandler.validateRunForMethod SS2
    //Generic_TriggerHandler.validateRunForMethod SS3
    //Generic_TriggerHandler.validateRunForMethod SS4
    //Generic_TriggerHandler.validateRunForMethod SS5
    //Generic_TriggerHandler.validateRunForMethod SS6
    //Generic_TriggerHandler.validateRunForMethod SS7
    //Generic_TriggerHandler.validateRunForMethod SS8
            list<Account> lstUpdateClientAccounts = [SELECT Id, Represents_Concern__c FROM Account WHERE ParentId IN :setConcernIds AND Id NOT IN :setExcludedClientIds AND Represents_Concern__c = true];
            if(lstUpdateClientAccounts != null && !lstUpdateClientAccounts.isEmpty()) {
                for(Account accIterator : lstUpdateClientAccounts) {
                    accIterator.Represents_Concern__c = false;
                    //accIterator.ParentId = null;
                }
                
                TriggerExecutionController.skipAccountTrigger(true);
                update lstUpdateClientAccounts;
                TriggerExecutionController.skipAccountTrigger(false);
            }
        }
        catch(Exception ex){
            ErrorLogger.writeError('SFDC', 'Account', 'AccountHierarchyManager.updateRepresentsConcern', ex.getTypeName(), ex.getMessage(), ''); // #RQ-005636 
        }
    }

    public static void updateKeyAttribute(List<Account> setofAccount){
            //Generic_TriggerHandler.validateRunForMethod SS1
    //Generic_TriggerHandler.validateRunForMethod SS2
    //Generic_TriggerHandler.validateRunForMethod SS3
    //Generic_TriggerHandler.validateRunForMethod SS4
    //Generic_TriggerHandler.validateRunForMethod SS5
    //Generic_TriggerHandler.validateRunForMethod SS6
    //Generic_TriggerHandler.validateRunForMethod SS7
    //Generic_TriggerHandler.validateRunForMethod SS8
        Set<Id> setofConcernId = new Set<Id>();
        List<Account> lstConcernUpdate = new List<Account>();

        try{
            if(setofAccount.size() > 0){
                for(Account acc : setofAccount){
                    if(acc.ParentId != null && acc.Represents_Concern__c == true){
                        setofConcernId.add(acc.ParentId);
                    }
                }
            }
            
            if(!setofConcernId.isEmpty()){
                    //Generic_TriggerHandler.validateRunForMethod SS1
    //Generic_TriggerHandler.validateRunForMethod SS2
    //Generic_TriggerHandler.validateRunForMethod SS3
    //Generic_TriggerHandler.validateRunForMethod SS4
    //Generic_TriggerHandler.validateRunForMethod SS5
    //Generic_TriggerHandler.validateRunForMethod SS6
    //Generic_TriggerHandler.validateRunForMethod SS7
    //Generic_TriggerHandler.validateRunForMethod SS8
                Map<Id,Account> mapofConcern = new Map<Id,Account>([SELECT Id,Attractiveness__c,Vertical__c,Industry__c,Value_Proposition__c,Sub_Segment__c,Sales_Channel__c,Customer_Size__c FROM Account WHERE Id IN : setofConcernId]);
                Account concern;
                for(Account acc : setofAccount){
                    if(acc.ParentId != null && acc.Represents_Concern__c == true){
                        concern = mapofConcern.containsKey(acc.ParentId) ? mapofConcern.get(acc.ParentId): null;
                        if( concern != null && (acc.Attractiveness__c != concern.Attractiveness__c || acc.Vertical__c != concern.Vertical__c || acc.Industry__c != concern.Industry__c
                            || acc.Value_Proposition__c != concern.Value_Proposition__c || acc.Sub_Segment__c != concern.Sub_Segment__c || acc.Sales_Channel__c != concern.Sales_Channel__c)){
                            
                            concern.Attractiveness__c = acc.Attractiveness__c ;
                            concern.Vertical__c = acc.Vertical__c ;
                            concern.Industry__c = acc.Industry__c ;
                            concern.Value_Proposition__c = acc.Value_Proposition__c ;
                            concern.Sub_Segment__c = acc.Sub_Segment__c ;
                            concern.Sales_Channel__c = acc.Sales_Channel__c ;
                            //concern.Customer_Size__c = acc.Customer_Size__c;
                            lstConcernUpdate.add(concern);
                        }
                    }
                }
            }

            if(!lstConcernUpdate.isEmpty()){
                Database.SaveResult[] result = database.update(lstConcernUpdate,false);
                ErrorLogger.writeErrors('CMD', 'Account', 'AccountHierarchyManager.updateKeyAttribute', result, lstConcernUpdate);
            }
        }catch(Exception ex){
            ErrorLogger.writeError('SFDC', 'Account', 'AccountHierarchyManager.updateKeyAttribute', ex.getTypeName(), ex.getMessage(), '');
        }
        
    }

    // Send To CMD Flag on contact when account recordtype changes from draft to Client Account -  SFSE-14282 
    public static void updateContact(Set<Id> setofAccount){
            //Generic_TriggerHandler.validateRunForMethod SS1
    //Generic_TriggerHandler.validateRunForMethod SS2
    //Generic_TriggerHandler.validateRunForMethod SS3
    //Generic_TriggerHandler.validateRunForMethod SS4
    //Generic_TriggerHandler.validateRunForMethod SS5
    //Generic_TriggerHandler.validateRunForMethod SS6
    //Generic_TriggerHandler.validateRunForMethod SS7
    //Generic_TriggerHandler.validateRunForMethod SS8
        try{
            if(!setofAccount.isEmpty()){
                List<Contact> conlist = [SELECT Id, AccountId FROM Contact WHERE AccountId IN : setofAccount];
                if(!setofAccount.isEmpty()){
                    Database.SaveResult[] result = database.update(conlist,false);
                    ErrorLogger.writeErrors('CMD', 'Account', 'AccountHierarchyManager.updateContact', result, conlist);
                }
            }    
        }catch(Exception ex){
            ErrorLogger.writeError('SFDC', 'Account', 'AccountHierarchyManager.updateContact', ex.getTypeName(), ex.getMessage(), '');
        }
        
    }
        //Generic_TriggerHandler.validateRunForMethod SS1
    //Generic_TriggerHandler.validateRunForMethod SS2
    //Generic_TriggerHandler.validateRunForMethod SS3
    //Generic_TriggerHandler.validateRunForMethod SS4
    //Generic_TriggerHandler.validateRunForMethod SS5
    //Generic_TriggerHandler.validateRunForMethod SS6
    //Generic_TriggerHandler.validateRunForMethod SS7
    //Generic_TriggerHandler.validateRunForMethod SS8
    
}