force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>+++ INTEGRATION: SCV +++</description>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Filtered Lookup Error: The specified &quot;Country&quot; is not of type &quot;Country&quot;.</errorMessage>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Accounts (Country)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#RQ-000235 - Help text added.
#RQ-000608 - Case Management Phase 1 - Removed Lookup filter.</description>
    <inlineHelpText>Primary Sales Contact for Maersk Line.</inlineHelpText>
    <label>z_Maersk Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004465- Sync&apos;ed with CMD, shows if a contact is active or not. Inactive means they are no longer employed by the account the contact record is linked to.
#RQ-004927</description>
    <inlineHelpText>Set to inactive when the contact is no longer employed by the company/account this contact is linked to. Never delete the contact in this scenario</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brands__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brands__c</fullName>
    <description>#RQ-002893-Captures the Liner Brands of the Contact.</description>
    <inlineHelpText>Captures the Brands of the Contact</inlineHelpText>
    <label>Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004927</description>
    <inlineHelpText>The language in which Customer would like to receive communication.</inlineHelpText>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abkhaz</fullName>
            </value>
            <value>
                <fullName>Afar</fullName>
            </value>
            <value>
                <fullName>Afrikaans</fullName>
            </value>
            <value>
                <fullName>Akan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Amharic</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Aragonese</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Assamese</fullName>
            </value>
            <value>
                <fullName>Avaric</fullName>
            </value>
            <value>
                <fullName>Avestan</fullName>
            </value>
            <value>
                <fullName>Aymara</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bambara</fullName>
            </value>
            <value>
                <fullName>Bashkir</fullName>
            </value>
            <value>
                <fullName>Basque</fullName>
            </value>
            <value>
                <fullName>Belorussian</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Bihari</fullName>
            </value>
            <value>
                <fullName>Bislama</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Breton</fullName>
            </value>
            <value>
                <fullName>Bulgarian</fullName>
            </value>
            <value>
                <fullName>Burmese</fullName>
            </value>
            <value>
                <fullName>Catalan</fullName>
            </value>
            <value>
                <fullName>Chamorro</fullName>
            </value>
            <value>
                <fullName>Chechen</fullName>
            </value>
            <value>
                <fullName>Chichewa, Chewa, Nyanja</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Unique_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_User_ID__c</fullName>
    <description>#Case_Mgt_v1:
Unique user ID of 6 characters, available only for Internal Contacts</description>
    <inlineHelpText>Unique 6-digit ID, in the format of 3 alphabet and 3 numeric digits</inlineHelpText>
    <label>Unique User ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ContactDataGeneratorHelper_Test.cls
/**
 * Helper class for generating Contact for all Liner Brands to be used as primary contact for an Account/Opportunity
 *
 * Date         Owner                                   Ref Number   Description
 **************************************************************************************************************************************
 * 17/02/2015   Deepa.Raman@ust-global.com              #RQ-000917   Move ALL test data generation to Helper classes.
 * 22/12/2015   Sandhya.Sambasivan@ust-global.com       #RQ-002247   Case trigger refactoring
 * 06/01/2016   Meghana.gupta@ust-global.com            #RQ-002192   Add method createCustomerContact by passing RunAs user
 * 12/12/2015   Sunu.Paul@ust-global.com                #PR-0055     Added data generator methods from Contact Trigger and also methods for creating Seago Contacts..
 * 03/05/2016   Sandhya.Sambasivan@ust-global.com       #RQ-003041   Added Linet Brand for internal contact
 * 12/08/2016   Jiji@UST                                #RQ-004057   RQ-004319 - Remove reference to Survey_Me__c, Primary_Contact__c field
 * 11/07/2019   Junaid.Khader@ust-global.com            RQ-010654    Removed reference of deprecated objects Trade_Interest__c & Customer_Subscription__c
 */
    
public class ContactDataGeneratorHelper_Test {      

    public static Contact customerContact = null,customerContactWithCountry;
    public static Contact nonShipPartyContact = null;
    public static Contact internalContact = null;
    public static Contact conObj,conObj2,conObj3,conSCLObj,conSCLObj2,conSCLObj3,conSEAObj,conSEAObj2,conSEAObj3;
    
    /**
    * Constructor
    **/    
    public ContactDataGeneratorHelper_Test () { 

    }   
    
    /**
    * Method to get Record Types of Contact to create Contacts.
    **/ 
    public static Map<String, ID> getContactRecordType () {
        Map<String, ID> ContRT = new Map<String, ID> ();
        for(RecordType r : [SELECT Id,Name FROM RecordType WHERE sObjectType = 'Contact' LIMIT 4]){
            ContRT.put(r.Name,r.id);
        }
        return ContRT;
    }
     
    public static Map<String, ID> ContactRecordTypeMap = getContactRecordType();
       
    /**
    * Method to create Customer Contact with specified Liner Brand.
    **/        
    public static Contact createCustomerContact(ID AccountID,String LinerBrand) {
        
        //Create primary contact
        customerContact =  createCustomerContact ( AccountID, LinerBrand, UserDataGeneratorHelper_Test.IntegrationUser);
        return customerContact;
    }
    
    /**
    * #RQ-002192 
    * Sealand contacts can be created by Sealand users only, hence passing runas user to method
    **/        
    public static Contact createCustomerContact(ID AccountID, String LinerBrand, User RunAsUser) {
        
        //customerContact = createCustomerContact(LinerBrand,AccountID,'MSLTestContact@testingContact1.com',true,false,RunAsUser);
        customerContact = createCustomerContact(LinerBrand,AccountID,'MSLTestContact@testingContact1.com',RunAsUser);
        return customerContact;
    }
    
    /**
    * Method to create Non-shipping Party Contact with specified Liner Brand
    **/ 
    public static Contact createNonShipPartyContact(ID AccountID,String LinerBrand) {
    
        //Create primary contact
        nonShipPartyContact =  new Contact();
        nonShipPartyContact.LastName = 'Test Class Contact' + Math.random();
        nonShipPartyContact.FirstName = LinerBrand ;
        nonShipPartyContact.Email = 'NSPTestContact1@testingcontact3.com';
        nonShipPartyContact.Preferred_Language__c = 'English';
        nonShipPartyContact.Liner_Brands__c = LinerBrand  ; 
        nonShipPartyContact.RecordTypeId = ContactRecordTypeMap.get('Non-shipping Party Contact');
        nonShipPartyContact.AccountId = AccountID;

        System.runAs(UserDataGeneratorHelper_Test.IntegrationUser){
            Database.Insert(nonShipPartyContact);
        }
        return nonShipPartyContact;
    }
    
    /**
    * Method to create Internal Contact with specified Liner Brand.Internal Contact does not need a brand specified.
    **/
    public static Contact createInternalContact(ID AccountID, String LinerBrand) {
    
        internalContact =  new Contact();
        internalContact.LastName = 'Test Class Contact' + Math.random();
        internalContact.FirstName = 'Inernal';
        internalContact.Email = 'InternalContact1@maersk.com';
        internalContact.Preferred_Language__c = 'English';
        internalContact.RecordTypeId = ContactRecordTypeMap.get('Internal Contact'); 
        internalContact.AccountId = AccountID;
        internalContact.Liner_Brands__c = LinerBrand ; //#RQ-003041 - Added Liner Brand
        internalContact.Unique_User_ID__c = 'TTT123'; //Feild avaible in preprod.
        
        System.runAs(UserDataGeneratorHelper_Test.IntegrationUser){
            Database.Insert(internalContact);
        }       
        return internalContact;
    }
    
    /**
    * Method to create Customer Contact with specified Liner Brand.
    **/        
    public static Contact createCustomerContactWithCountry(ID AccountId,String LinerBrand, Id CountryId) {
        
        //Create primary contact
        customerContactWithCountry =  new Contact();
        customerContactWithCountry.LastName = 'Test Class Contact' + Math.random();
        customerContactWithCountry.FirstName = LinerBrand ;
        customerContactWithCountry.Email = 'TestContact@testingcontact3.com';
        customerContactWithCountry.Preferred_Language__c = 'English';
        //customerContactWithCountry.Primary_Contact__c = true;
        customerContactWithCountry.Liner_Brands__c = LinerBrand ; 
        customerContactWithCountry.RecordTypeId = ContactRecordTypeMap.get('Customer Contact');
        customerContactWithCountry.AccountId = AccountId;
        customerContactWithCountry.Country__c = CountryId;
 
        System.runAs(UserDataGeneratorHelper_Test.MLLIntegrationUser){
            Database.Insert(customerContactWithCountry);
        }
        return customerContactWithCountry;
    }
    
    /*
    * Method to create Customer Contact with specified Liner Brand, Email and Primary Flag 
    **/        
    //public static Contact createCustomerContact(String LinerBrand,Id AccountID,String ContactEmail,Boolean PrimaryFlag,Boolean Surveyme,User RunAsUser) {
    public static Contact createCustomerContact(String LinerBrand,Id AccountID,String ContactEmail,User RunAsUser) {
        
        //Create primary contact
        customerContact =  new Contact();
        customerContact.LastName = 'Test Class Contact' + Math.random();
        customerContact.FirstName = LinerBrand ;
        customerContact.Email = ContactEmail;
        customerContact.Preferred_Language__c = 'English';
        //customerContact.Primary_Contact__c = PrimaryFlag ;
        customerContact.Liner_Brands__c = LinerBrand ;
        customerContact.RecordTypeId = ContactRecordTypeMap.get('Customer Contact');
        customerContact.AccountId = AccountID;
		customerContact.Contact_Status__c = 'Active';
        System.runAs(RunAsUser){
            Database.Insert(customerContact);
        } 
        System.debug('*********Contact Last Name :'+customerContact.LastName+'Email:'+customerContact.Email+'Liner Brand:'+customerContact.Liner_Brands__c);    

        return customerContact;
    }         
}