force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>+++ INTEGRATION: SCV +++</description>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Filtered Lookup Error: The specified &quot;Country&quot; is not of type &quot;Country&quot;.</errorMessage>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Accounts (Country)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004465- Sync&apos;ed with CMD, shows if a contact is active or not. Inactive means they are no longer employed by the account the contact record is linked to.
#RQ-004927</description>
    <inlineHelpText>Set to inactive when the contact is no longer employed by the company/account this contact is linked to. Never delete the contact in this scenario</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brands__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brands__c</fullName>
    <description>#RQ-002893-Captures the Liner Brands of the Contact.</description>
    <inlineHelpText>Captures the Brands of the Contact</inlineHelpText>
    <label>Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Unique_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_User_ID__c</fullName>
    <description>#Case_Mgt_v1:
Unique user ID of 6 characters, available only for Internal Contacts</description>
    <inlineHelpText>Unique 6-digit ID, in the format of 3 alphabet and 3 numeric digits</inlineHelpText>
    <label>Unique User ID</label>
    <length>6</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ContactData_Test.cls
/**
* Author   : Ragu
* Purpose  : Utility test class for creating Account related test data. 
*
* Revision Ref Number  Date        Owner                   Description
* -------- ----------  ----------- -------------------     -----------
* 1.0      RQ-002633   06-May-2016 Ragu@UST                Created.
* 2.0      RQ-004366   29-May-2017 Hitha@UST               Updated to make contact status as "Active".
* 3.0      RQ-005312   12-May-2017 Hitha@UST               Updated to improve code coverage  
* 4.0      SPI-100     13-Jun-2022 Ronnie@SF               Removed brand hardcoding
*/

@isTest
public class ContactData_Test {
    
    public static boolean bCreate = true;
    public static integer iNumberOfContacts = 5;
    public static list<Contact> lstContacts;
    
    // Use this accInstance if you have already created an Account and you wanted to create Contacts for it.
    public static Account accInstance = null;
    
    public static testMethod void createCustomerContacts() {
        populateCommonContactFields();
        Id customerRTId = StaticFactory.getRecordTypeIdByName('Contact', 'Customer Contact');
        for(Contact conIterator : lstContacts) {
            conIterator.LastName = 'Customer Contact' + Math.random() + DateTime.now().millisecond(); 
            conIterator.RecordTypeId = customerRTId;
        }
        if(bCreate) {
            insert lstContacts;
        }
        AccountData_Test.createEntitlements();
    }
    
    public static testMethod void createInternalContacts() {
        AccountData_Test.iNumberOfAccounts = 1;
        AccountData_Test.createUnassignedAccounts();
        ContactData_Test.accInstance =AccountData_Test.lstAccounts[0];
        
        populateCommonContactFields();
        
        Id internalRTId = StaticFactory.getRecordTypeIdByName('Contact', 'Internal Contact');
        Integer uniqueUidCounter = 1;
        for(Contact conIterator : lstContacts) {
            conIterator.LastName = 'Internal Contact' + Math.random() + DateTime.now().millisecond(); 
            conIterator.Unique_User_ID__c = 'UId' + uniqueUidCounter;
            conIterator.Email = DateTime.now().millisecond() + 'TestContact' + Math.random() + '@maersk.com'; //RQ-005312
            conIterator.RecordTypeId = internalRTId;
            uniqueUidCounter++;
        }
        if(bCreate) {
            insert lstContacts;
        }
    }
    
    public static testMethod void createNonShippingPartyContacts() {
        populateCommonContactFields();
        Id nonShippingRTId = StaticFactory.getRecordTypeIdByName('Contact', 'Non-shipping Party Contact');
        for(Contact conIterator : lstContacts) {
            conIterator.LastName = 'Non-shipping Party' + Math.random() + DateTime.now().millisecond(); 
            conIterator.RecordTypeId = nonShippingRTId;
        }
        if(bCreate) {
            insert lstContacts;
        }
    }
    
    private static testMethod void populateCommonContactFields() {
        if(accInstance == null) {
            AccountData_Test.iNumberOfAccounts = 1;
            AccountData_Test.createClientAccounts();
            accInstance =AccountData_Test.lstAccounts[0];
        }
        
        lstContacts = new list<Contact>();
        for(Integer i=0; i<iNumberOfContacts; i++) {
            Contact conIterator = new Contact();
            conIterator.AccountId = accInstance.Id;
            
            Double randomVal = Math.random() * 100;
            Integer roundval = Math.round(randomVal);
            
            conIterator.Email = DateTime.now().millisecond() + 'TestContact' + Math.random() + '@test.com';
            conIterator.Phone = '+44 123412' + roundval;
            conIterator.FirstName = 'Test' + Math.random() + DateTime.now().millisecond();
            conIterator.Liner_Brands__c = BrandUtilities.MAERSKLINE;
            conIterator.Country__c = accInstance.Country__c;
            conIterator.Contact_Status__c = 'Active';
            
            lstContacts.add(conIterator);
        }
    }
}