force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>+++ INTEGRATION: SCV +++</description>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Filtered Lookup Error: The specified &quot;Country&quot; is not of type &quot;Country&quot;.</errorMessage>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Accounts (Country)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004465- Sync&apos;ed with CMD, shows if a contact is active or not. Inactive means they are no longer employed by the account the contact record is linked to.
#RQ-004927</description>
    <inlineHelpText>Set to inactive when the contact is no longer employed by the company/account this contact is linked to. Never delete the contact in this scenario</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Geography__c.Type_Of_Location__c</field>
            <operation>equals</operation>
            <value>Country</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Geography__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brands__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brands__c</fullName>
    <description>#RQ-002893-Captures the Liner Brands of the Contact.</description>
    <inlineHelpText>Captures the Brands of the Contact</inlineHelpText>
    <label>Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DisputesEventHandlerTest.cls
/**
* Author   : Vivek.agrawal@maersk
* Purpose  : Test Class for Dispute Event Handler and Dispute Trigger
 *
* Revision Ref Number  Date         Owner                   Description
* -------- ----------  -----------  -------------------     -----------
 * 1.0      SS-4473     05-March-2022 Vivek.agrawal@Maersk    Test Class DisputeEventHandlerTest created to test the creation of disputes cases from platform event
 * 2.0      SPI-100     13-06-2022    Ronnie@SF               Removed brand hardcoding
*/


@isTest 
public class DisputesEventHandlerTest {

    public static testmethod void testDisputeCasesInsert() {

        Disputes_Event__e thisEvent = new Disputes_Event__e(Json_1__c = '{"ohpDispute_id":"0932","statuscode" : "10","createdSource" : "OHP","alternateMailId":"","statusCode":"10","statusDescription":"Re","companyCode":"1000","contactPerson":"kamala kannan","contactEmail":"hunt1@gmail.com","invoiceNumber":"4813052074","eventType":"Insert"}');

        Test.startTest();
                
        // Publish test event
        Database.SaveResult sr = EventBus.publish(thisEvent);
            
        Test.stopTest();
    }

    public static testmethod void testDisputeCasesUpdate() {

        TriggerExecutionController.skipAllTriggers(true);
        
        AccountData_Test.iNumberOfAccounts = 1;
        AccountData_Test.createClientAccounts();
        Account accInstance =AccountData_Test.lstAccounts[0];
        //ContactData_Test.populateCommonContactFields();
         Id customerRTId = StaticFactory.getRecordTypeIdByName('Contact', 'Customer Contact');
         Contact conInstance = new Contact();
           conInstance.AccountId = accInstance.Id;
            conInstance.LastName = 'Test Contact Dispute'; 
            conInstance.RecordTypeId = customerRTId;
            conInstance.Email = DateTime.now().millisecond() + 'TestContact' + Math.random() + '@test.com';
            conInstance.Phone = '+44 123412' ;
            conInstance.FirstName = 'Test' + Math.random() + DateTime.now().millisecond();
        conInstance.Liner_Brands__c = BrandUtilities.MAERSK;
            conInstance.Country__c = accInstance.Country__c;
            conInstance.Contact_Status__c = 'Active';
       
        insert conInstance;
        CaseData_Test.bCreate = false;
        CaseData_Test.iNumberOfCases = 3;
        CaseData_Test.conInstance = conInstance;
        
        list<Case> lstCases = new list<Case>();
        CaseData_Test.createDisputecases();
        lstCases.addAll(CaseData_Test.lstCases);
        
        TriggerExecutionController.skipAllTriggers(false);
        insert lstCases; 
        system.debug('--lstCases'+lstCases[1].status);

        Test.startTest();

        List<Case> childList = [select Id, Disputed_Invoice_Number__c, ParentId from Case where Id in(:lstCases[1].Id)];
       
        String invoiceNumber = childList[0].Disputed_Invoice_Number__c;
        system.debug('--invoice Number'+invoiceNumber);

        Disputes_Event__e thisEvent2 = new Disputes_Event__e(Json_1__c = '{"ohpDispute_id":"0932","statusCode":"20","alternateMailId":"","statusDescription":"Re","companyCode":"1000","contactPerson":"kamala kannan","contactEmail":"hunt1@gmail.com","invoiceNumber":"'+invoiceNumber+'","eventType":"Update", "noteDescription":"test","changedTs":"2022-05-25T15:12:17Z"}');
        Disputes_Event__e thisEvent3 = new Disputes_Event__e(Json_1__c = '{"ohpDispute_id":"0933","statusCode":"63","alternateMailId":"","statusDescription":"Re","companyCode":"1000","contactPerson":"kamala kannan","contactEmail":"hunt1@gmail.com","invoiceNumber":"'+invoiceNumber+'","eventType":"Update", "noteDescription":"test","changedTs":"2022-05-25T15:14:17Z"}');
        Disputes_Event__e thisEvent4 = new Disputes_Event__e(Json_1__c = '{"ohpDispute_id":"0934","statusCode":"75","alternateMailId":"","statusDescription":"Re","companyCode":"1000","contactPerson":"kamala kannan","contactEmail":"hunt1@gmail.com","invoiceNumber":"'+invoiceNumber+'","eventType":"Update", "noteDescription":"test","changedTs":"2022-05-25T15:13:17Z"}');
        
        // Publish test event
        Database.SaveResult sr2 = EventBus.publish(thisEvent2);
        Database.SaveResult sr3 = EventBus.publish(thisEvent3);
        Database.SaveResult sr4 = EventBus.publish(thisEvent4);

        Test.stopTest();
    }
    
    public static testmethod void testDisputeCasesUpdate2() {

        TriggerExecutionController.skipAllTriggers(true);
        
        AccountData_Test.iNumberOfAccounts = 1;
        AccountData_Test.createClientAccounts();
        Account accInstance =AccountData_Test.lstAccounts[0];
        //ContactData_Test.populateCommonContactFields();
         Id customerRTId = StaticFactory.getRecordTypeIdByName('Contact', 'Customer Contact');
         Contact conInstance = new Contact();
           conInstance.AccountId = accInstance.Id;
            conInstance.LastName = 'Test Contact Dispute'; 
            conInstance.RecordTypeId = customerRTId;
            conInstance.Email = DateTime.now().millisecond() + 'TestContact' + Math.random() + '@test.com';
            conInstance.Phone = '+44 123412' ;
            conInstance.FirstName = 'Test' + Math.random() + DateTime.now().millisecond();
        conInstance.Liner_Brands__c = BrandUtilities.MAERSK;
            conInstance.Country__c = accInstance.Country__c;
            conInstance.Contact_Status__c = 'Active';
       
        insert conInstance;
        CaseData_Test.bCreate = false;
        CaseData_Test.iNumberOfCases = 3;
        CaseData_Test.conInstance = conInstance;
        
        list<Case> lstCases = new list<Case>();
        CaseData_Test.createDisputecases();
        lstCases.addAll(CaseData_Test.lstCases);
        
        TriggerExecutionController.skipAllTriggers(false);
        insert lstCases; 
        system.debug('--lstCases'+lstCases[1].status);
        CaseComment ccom =  new CaseComment(commentBody = 'Test 1', parentId = lstCases[1].Id);
        insert ccom;

        Test.startTest();

        List<Case> childList = [select Id, Disputed_Invoice_Number__c, ParentId from Case where Id in(:lstCases[1].Id)];
       
        String invoiceNumber = childList[0].Disputed_Invoice_Number__c;
        system.debug('--invoice Number'+invoiceNumber);

        Disputes_Event__e thisEvent3 = new Disputes_Event__e(Json_1__c = '{"ohpDispute_id":"0933","statusCode":"63","alternateMailId":"","statusDescription":"Re","companyCode":"1000","contactPerson":"kamala kannan","contactEmail":"hunt1@gmail.com","invoiceNumber":"'+invoiceNumber+'","eventType":"Update", "noteDescription":"test","changedTs":"2022-05-25T15:14:17Z"}');
        Disputes_Event__e thisEvent4 = new Disputes_Event__e(Json_1__c = '{"ohpDispute_id":"0934","statusCode":"75","alternateMailId":"","statusDescription":"Re","companyCode":"1000","contactPerson":"kamala kannan","contactEmail":"hunt1@gmail.com","invoiceNumber":"'+invoiceNumber+'","eventType":"Update", "noteDescription":"test","changedTs":"2022-05-25T15:13:17Z"}');
        
        // Publish test event
        Database.SaveResult sr3 = EventBus.publish(thisEvent3);
        Database.SaveResult sr4 = EventBus.publish(thisEvent4);

        Test.stopTest();
    }
 
    @isTest
     static void testgetUserOwner(){
      
         Map<String, String> processorMap = new Map<String, String>{'CCP008' => '2345678101'};
         Test.startTest();
          DisputesEventHandler.getUserOwner(processorMap);
         Test.stopTest();
     }



}