force-app/main/default/objects/Account/fields/Customer_Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status_Reason__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004162 
#RQ-004927</description>
    <inlineHelpText>Indicates the reason why a customer code has been deactivated (made inactive). This field is populated via integration from CMD</inlineHelpText>
    <label>Customer Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SCV_Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Customer Not In Use</fullName>
            </value>
            <value>
                <fullName>Customer Out Of Business</fullName>
            </value>
            <value>
                <fullName>Difficult Collections</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Legally Denied Party</fullName>
            </value>
            <value>
                <fullName>Unethical Behaviour</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Missing Or Invalid Mandatory Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Status__c.field-meta.xml
<CustomField>
    <fullName>SCV_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot;
#RQ-000235 - Help text added.
#RQ-004162 - Changed Field label and help text
#RQ-004927.</description>
    <inlineHelpText>Indicates if this customer is active or not as per Customer Master Data definitions</inlineHelpText>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client_Account.recordType-meta.xml
<RecordType>
    <fullName>Client_Account</fullName>
    <active>true</active>
    <description>Client Accounts are customers who place bookings with the company and WILL have an SCV code. Client Accounts are mastered in SCV.</description>
    <label>Client Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004465- Sync&apos;ed with CMD, shows if a contact is active or not. Inactive means they are no longer employed by the account the contact record is linked to.
#RQ-004927</description>
    <inlineHelpText>Set to inactive when the contact is no longer employed by the company/account this contact is linked to. Never delete the contact in this scenario</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer_Contact.recordType-meta.xml
<RecordType>
    <fullName>Customer_Contact</fullName>
    <active>true</active>
    <description>A person from the customer&apos;s organisation</description>
    <label>Customer Contact</label>
</RecordType>

force-app/main/default/classes/Batch_InactiveContact_Deletion_Test.cls
/**
 * Version  Date           Owner                    RQ#           Description
 ****************************************************************************************************************************************
 * 1.0      
 * 2.0      15/06/2022     Ronnie@SF                SPI-100       Removed brand hardcoding
 */

@isTest
public class Batch_InactiveContact_Deletion_Test {
    
    @testSetup static void setup() {
        Test.startTest();
       TriggerExecutionController.skipAllTriggers(true);
        //create test account1-Account with Transactional data
        Account ClientAccount = TestBusinessHelper.createAccount('Client_Account', true);
        
        //Relate a Contact with Account1
        Contact MSLContact =TestBusinessHelper.createContact(clientAccount, 'Customer_Contact', BrandUtilities.MAERSKLINE, true);
        Opportunity mslOppty = TestBusinessHelper.createOpportunity(clientAccount, null, null, 'ShippingCargoServices', BrandUtilities.MAERSKLINE, true);
        //Relate a SalesMetrics with Account1
        List <Product2> prodList = DataGeneratorHelper1_Test.createProduct2(1,'A','DE','MSL');
        
        //Relate tasks & events with Account1
        List<Task> msltask = DataGeneratorHelper1_Test.createTasks( 2, ClientAccount.id );
        msltask[0].WhoId=MSLContact.id;
        update msltask;
        List<Event> mslevent = DataGeneratorHelper1_Test.createEvents( 1, ClientAccount.id ); 
        mslevent[0].WhoId=MSLContact.id;
        update mslevent;
        
        ClientAccount.SCV_Status__c = 'Inactive';
        ClientAccount.Customer_Status_Reason__c='Duplicate';
        update ClientAccount;
        /*
        //Create Test Account2 - Account with No transactional data
        Account ClientAcc2 = AccountDataHelper_Test.createClntAccountWithMSLUser();
        
        ClientAcc2.SCV_Status__c = 'Inactive';
        ClientAccount.Customer_Status_Reason__c='Duplicate';
        update ClientAcc2; 
        */
        /* MSLContact.Contact_Status__c = 'Inactive';
        MSLContact.email = '1111111@gmail.co';
        update MSLContact;*/
        TriggerExecutionController.skipAllTriggers(false);
        Test.stopTest();
    }
    
    @isTest static void testBatchInactiveAccountsDeletion() {
        
        User usrRecord = new User(id=UserInfo.getUserId()); // Run as System admin User since batch will be invoked by Data Interface user which is admin User
        System.runAs(usrRecord){
            Test.startTest();
            Account clientAcc1 = [ SELECT Id,Name FROM Account Limit 1 ];
            system.debug('$$$clientAcc1: '+ clientAcc1);
            List<Contact> lstContact = [SELECT Id,Name FROM Contact limit 1 ];
            InActiveContact_Deletion_Batch batchTest = new InActiveContact_Deletion_Batch();
            Database.executeBatch( batchTest); 
            batchTest.execute(null,lstContact);
            InactiveContact_Deletion_Schedule schClass = new InactiveContact_Deletion_Schedule();
            String strSchTime = '0 8 13 14 3 ? *';
            System.schedule( 'deleteInactiveAccount', strSchTime, schClass );
            Test.stopTest();
        }
    }
}