force-app/main/default/objects/Account/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004162 
#RQ-004927</description>
    <externalId>true</externalId>
    <inlineHelpText>The SAP Fact code. This field is populated from CMD via Integration</inlineHelpText>
    <label>Customer Code</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact_Status__c.field-meta.xml
<CustomField>
    <fullName>Contact_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004465- Sync&apos;ed with CMD, shows if a contact is active or not. Inactive means they are no longer employed by the account the contact record is linked to.
#RQ-004927</description>
    <inlineHelpText>Set to inactive when the contact is no longer employed by the company/account this contact is linked to. Never delete the contact in this scenario</inlineHelpText>
    <label>Contact Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <description>Backend field created to store the customer code for the contacts failed to insert because account not existed. This value will be cleared once contact tagged to account.</description>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer_Contact.recordType-meta.xml
<RecordType>
    <fullName>Customer_Contact</fullName>
    <active>true</active>
    <description>A person from the customer&apos;s organisation</description>
    <label>Customer Contact</label>
</RecordType>

force-app/main/default/classes/BatchAssignContactsToAccounts.cls
/*
* Author   : Shilpa
* Purpose  : Batch class to assigned accounts to contacts coming from CMD which is failed . 
*/

global class BatchAssignContactsToAccounts implements Database.Batchable<sObject>{ 
    
    /*private List<Id> contactIds;
    
    global BatchAssignContactsToAccounts(List<Id> contactIds) {
        this.contactIds = contactIds;
    }*/
    
    global Database.QueryLocator start(Database.BatchableContext BC) { 
         
        Id Customer_Contact = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Customer_Contact').getRecordTypeId();
        String query = 'SELECT Id, Name, Customer_Code__c, Contact_Status__c,RecordTypeId, AccountId FROM Contact WHERE Customer_Code__c != null AND Contact_Status__c = \'Inactive\' AND AccountId = null AND RecordTypeId =\'' + Customer_Contact + '\'';
        return Database.getQueryLocator(query);
        
    } 
    
    global void execute(Database.BatchableContext BC, List<Contact> conlist) {
        Set<String> setOfcustomerCode = new Set<String>();
        map<String,Account> mapOfAccount = new map<String,Account>();
        List<Contact>listToUpdateContact = new list<Contact>(); 
        for(Contact c : conlist){
            setOfcustomerCode.add(c.Customer_Code__c);
        }
       
        for(Account acc : [Select Id,name,Customer_Code__c from Account where Customer_Code__c IN: setOfcustomerCode]){
            mapOfAccount.put(acc.Customer_Code__c,acc);
        }
       if(!mapOfAccount.isEmpty()){
          for(Contact con :conlist) {
              if(mapOfAccount.containskey(con.Customer_Code__c)){
                  con.AccountId = mapOfAccount.get(con.Customer_Code__c).Id;
                  con.Customer_Code__c ='';
                  con.Contact_Status__c = 'Active';
                  listToUpdateContact.add(con);
              }  
           }
       }
       if(!listToUpdateContact.isEmpty()){
          try{
            Database.Update(listToUpdateContact); 
        } Catch(Exception e) {
            ErrorLogger.writeErrors( 'SFDC', 'Contact', 'BatchAssignContactsToAccounts', new list<Exception>{e});
        }
        }
    }
    global void finish(Database.BatchableContext BC) { 
        
       
    } 
    
}