force-app/main/default/objects/Account/fields/Is_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Is_Opportunity__c</fullName>
    <label>No. of Opportunity</label>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsConcern__c.field-meta.xml
<CustomField>
    <fullName>IsConcern__c</fullName>
    <description>#RQ-000026 - To identify if Account is Concern Account.</description>
    <formula>IF (BEGINS( SCV_Code__c, &quot;***&quot; ),&apos;TRUE&apos;, &apos;FALSE&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>IsConcern</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration&quot; .
Unique customer number shared across numerous Maersk systems. Populated by custom Java components in the middleware layer. Should be read-only to users using FLS so there is no chance of modification by anyone other than the Master Data Interface User.
#RQ-002042-Reduced the text characters to 11
#RQ-004927.</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal system identifier from SCV</inlineHelpText>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Status__c.field-meta.xml
<CustomField>
    <fullName>SCV_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot;
#RQ-000235 - Help text added.
#RQ-004162 - Changed Field label and help text
#RQ-004927.</description>
    <inlineHelpText>Indicates if this customer is active or not as per Customer Master Data definitions</inlineHelpText>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Batch_Inactive_ClientAcc_Del_Test.cls
/*
---------------------------------------------------------------------------------------------------------------------------
 * Author: Cognizant Technology Solutions
 * Purpose:  This class contains unit tests for validating the behavior of Apex classe Batch_Inactive_ClientAccount_Deletion and Scheduled_InactiveAccountDelete
-----------------------------------------------------------------------------------------------------------------------------

*Version   Date           Owner                                   Description
**************************************************************************************************************************************
* 1.0      06/12/2015   dinesh.moorthy@ust-global.com           #RQ-002192  Rename test class, add comments and optimization

*/
@isTest
private class Batch_Inactive_ClientAcc_Del_Test {
    
    static testMethod void Test_Batch_Inactive_ClientAccount_Delete() {        
     
        // create test account
        Account acc = AccountDataHelper_Test.createClientAccount( null, 'Inactive' );          
        
        Test.startTest();  
        
        // test scheduler class Scheduled_InactiveAccountDelete
        Scheduled_InactiveAccountDelete schController= new Scheduled_InactiveAccountDelete();
        String t = '0 0 * * * ? *';
        System.schedule( 'Inactive Account Deletion', t, schController );
        
        // test batch class
        Batch_Inactive_ClientAccount_Deletion controller = new Batch_Inactive_ClientAccount_Deletion();       
        controller.query = 'SELECT id, SCV_Code__c from Account where SCV_Status__c = \'Inactive\' and IsConcern__c = \'FALSE\' and Is_Opportunity__c = 0 limit 100';
             
        Id ApexId = Database.Executebatch( controller, 200 );  

        // verify batch job execution
        AsyncApexJob BatchJob = [ Select Id, Status, NumberOfErrors from AsyncApexJob where Id = :ApexId ];
        System.Assert( BatchJob != null );
        
        Test.stopTest();  
    } 
    
    static testMethod void Test_Batch2() {        
     
        // create test account
        Account acc = AccountDataHelper_Test.createClientAccount( null, 'Inactive' );          
        
        // create tasks & events for the test account 
        DataGeneratorHelper1_Test.createTasks( 2, acc.id );
        DataGeneratorHelper1_Test.createEvents( 1, acc.id );
        
        // account with an event & task will not be deleted by the batch
        Test.startTest(); 
        
        Batch_Inactive_ClientAccount_Deletion controller = new Batch_Inactive_ClientAccount_Deletion();       
        controller.query = 'SELECT id, SCV_Code__c from Account where SCV_Status__c = \'Inactive\' and IsConcern__c = \'FALSE\' and Is_Opportunity__c = 0 limit 100';
             
         Id ApexId = Database.Executebatch( controller, 200 );  

        // verify batch job execution
        AsyncApexJob BatchJob = [ Select Id, Status, NumberOfErrors from AsyncApexJob where Id = :ApexId ];
        System.Assert( BatchJob != null );       

        Test.stopTest();  

    } 
    
}