force-app/main/default/objects/Account/fields/MSL_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>MSL_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#Safmarine_United
Set through one-way integration with master data system SCV / SMDS, therefore should be read only for all users.
#RQ-004168 - Updated FLS</description>
    <inlineHelpText>The Maersk Line sales person responsible for this Account.</inlineHelpText>
    <label>Maersk Owner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <infoMessage>Please select an Internal User</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts_MSL_Owned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>#RQ-000235 - Help text added.
#RQ-000608 - Case Management Phase 1 - Removed Lookup filter.</description>
    <inlineHelpText>Primary Sales Contact for Maersk Line.</inlineHelpText>
    <label>z_Maersk Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration&quot; .
Unique customer number shared across numerous Maersk systems. Populated by custom Java components in the middleware layer. Should be read-only to users using FLS so there is no chance of modification by anyone other than the Master Data Interface User.
#RQ-002042-Reduced the text characters to 11
#RQ-004927.</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal system identifier from SCV</inlineHelpText>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brand__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brand__c</fullName>
    <description>#Safmarine_United 
#PR-0047: Added MCC Brand Value to this pick list.
#PR-0055-Added Seago value to the picklist .</description>
    <inlineHelpText>Captures the Brand of the Contact.</inlineHelpText>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brands__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brands__c</fullName>
    <description>#RQ-002893-Captures the Liner Brands of the Contact.</description>
    <inlineHelpText>Captures the Brands of the Contact</inlineHelpText>
    <label>Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alianca</fullName>
            </value>
            <value>
                <fullName>Hamburg Sud</fullName>
            </value>
            <value>
                <fullName>Maersk Line</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>Seago</fullName>
            </value>
            <value>
                <fullName>Sealand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot; 
#RQ-004927</description>
    <inlineHelpText>The language in which Customer would like to receive communication.</inlineHelpText>
    <label>Preferred Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Abkhaz</fullName>
            </value>
            <value>
                <fullName>Afar</fullName>
            </value>
            <value>
                <fullName>Afrikaans</fullName>
            </value>
            <value>
                <fullName>Akan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Amharic</fullName>
            </value>
            <value>
                <fullName>Arabic</fullName>
            </value>
            <value>
                <fullName>Aragonese</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Assamese</fullName>
            </value>
            <value>
                <fullName>Avaric</fullName>
            </value>
            <value>
                <fullName>Avestan</fullName>
            </value>
            <value>
                <fullName>Aymara</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bambara</fullName>
            </value>
            <value>
                <fullName>Bashkir</fullName>
            </value>
            <value>
                <fullName>Basque</fullName>
            </value>
            <value>
                <fullName>Belorussian</fullName>
            </value>
            <value>
                <fullName>Bengali</fullName>
            </value>
            <value>
                <fullName>Bihari</fullName>
            </value>
            <value>
                <fullName>Bislama</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Breton</fullName>
            </value>
            <value>
                <fullName>Bulgarian</fullName>
            </value>
            <value>
                <fullName>Burmese</fullName>
            </value>
            <value>
                <fullName>Catalan</fullName>
            </value>
            <value>
                <fullName>Chamorro</fullName>
            </value>
            <value>
                <fullName>Chechen</fullName>
            </value>
            <value>
                <fullName>Chichewa, Chewa, Nyanja</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++ Do not change this field without reviewing impact with master data integration. SFMC-7706</description>
    <externalId>true</externalId>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityDeleteOverrideExtension_Test.cls
/*************************************************************************************************************************************************
 * Description : This is a test class created to cover below class :
 *                      1.  OpportunityDeleteOverrideExtension
 *                    
 * Version Date         Owner                                   Ref Number    Description
 **************************************************************************************************************************************
 * 1.0     17/5/2014    UST                                                   Modified as part of cleanup Activity
 * 2.0     14/10/2014   revathy.sudhindran@ust-global.com       #RQ-000058    Comented the statements containing Potential_FFE__c field of Quote Object.
 * 3.0     08/12/2014   Krishnamoorthi.murugesan@ust-global.com #RQ-000828    Removed PPVVC from Opportunity
 * 4.0     26/04/2017   Rathish.Rajendran@ust-global.com        #RQ-004168    Added a user record to Account.MSL_Account_Owner__c. Removed fields Account.Export_Rep__c and MSL_Export_Rep_Maersk_Id__c.
 * 5.0     06/06/2019   manjunath.c.holekade@maersk.com         #RQ-010819	  Removal of references of deprecated fields 
 * 6.0     08/06/2022   Ronnie@SF                               SPI-100       Removed brand hardcoding
 **************************************************************************************************************************************************/
 

@isTest
private class OpportunityDeleteOverrideExtension_Test
{
    
    testmethod static void checkDeletion()
    {
        TriggerExecutionController.skipAllTriggers(true);
        CreateIntegrationUserData_Test.initializeIntegrationUser();
        User demoUser = CreateIntegrationUserData_Test.integrationUser;
        Test.starttest();
        Account demoAcccount = new Account();
        demoAcccount.Name ='demoAcc';
        demoAcccount.Type = 'BCO';
        demoAcccount.SCV_Code__c = '2242348789';
        demoAcccount.MSL_Account_Owner__c =  CreateIntegrationUserData_Test.integrationUser.Id;                
        // demoAcccount.Export_Rep__c=CreateIntegrationUserData_Test.integrationUser.Id;
        // demoAcccount.MSL_Export_Rep_Maersk_Id__c = 'MSL123';
        System.runAs(CreateIntegrationUserData_Test.integrationUser) {
            insert demoAcccount;
        }
        Contact cont=new Contact(FirstName = 'Sample', LastName = 'test', Liner_Brands__c = BrandUtilities.MAERSKLINE, Account = demoAcccount, AccountId = demoAcccount.Id, Email = 're.sudh@hotmail.play', Preferred_Language__c = 'English');
        System.runAs(CreateIntegrationUserData_Test.integrationUser) {
            insert cont;
        }
        TriggerExecutionController.skipAllTriggers(false);
        Opportunity oppObj = new Opportunity();
        oppObj.Name = 'test opportunity';
        oppObj.AccountId = demoAcccount.Id;
        oppObj.CloseDate = date.today()+30;
        oppObj.StageName = Label.LeadLabel;
        oppObj.Primary_Contact__c = cont.id;
        oppObj.Liner_Brand__c = BrandUtilities.MAERSKLINE;
         oppObj.Expected_Handling_Rounds__c = 2;
        insert oppObj;
        
        Quote quoteObj = new Quote();
        quoteObj.Name = 'Test Quote';
        //quoteObj.Potential_FFE__c=100;
        quoteObj.Effective_From_Date__c = date.today();
        quoteObj.ExpirationDate = date.today() + 30;
        quoteObj.Segment__c = 'BCO';
        quoteObj.OpportunityId = oppObj.Id;
        insert quoteObj;
        
        try{
            Test.setCurrentPageReference(Page.OpportunityDeleteOverride);
            ApexPages.currentPage().getParameters().put('Id',oppObj.Id);
            ApexPages.StandardController lStandardOppObj = new ApexPages.StandardController(oppObj);
            OpportunityDeleteOverrideExtension lDeleteOppObj = new OpportunityDeleteOverrideExtension(lStandardOppObj);
            lDeleteOppObj.deleteAction();
             Integer lOpportunityCount = [SELECT count() FROM Opportunity WHERE Id = :oppObj.Id];
            System.assert(lOpportunityCount>0, true);
            lDeleteOppObj.redirectUrl();
            System.assertEquals(ApexPages.currentPage().getParameters().get('Id'),String.valueOf(oppObj.Id));
            
            delete quoteObj;
                Test.setCurrentPageReference(Page.OpportunityDeleteOverride);
            ApexPages.currentPage().getParameters().put('Id', oppObj.Id);
            lStandardOppObj = new ApexPages.StandardController(oppObj);
            lDeleteOppObj = new OpportunityDeleteOverrideExtension(lStandardOppObj);
            lDeleteOppObj.deleteAction();
            lOpportunityCount = [SELECT count() FROM Opportunity WHERE Id = :oppObj.Id];
            system.debug('integer'+lOpportunityCount);
        }catch(Exception ex){
            
        }
        Test.stopTest();
    }
}