force-app/main/default/objects/Account/fields/Represents_Concern__c.field-meta.xml
<CustomField>
    <fullName>Represents_Concern__c</fullName>
    <defaultValue>false</defaultValue>
    <description>#RQ-004705
As part of the interim solution will create a new field called &quot;Represents Concern&quot; and this is to show the equivalent of the &quot;Is-Concern&quot; relationship that master data will have</description>
    <inlineHelpText>When set to true this highlights that this SCV code is the equivalent of the concern level account</inlineHelpText>
    <label>Represents Concern</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Code__c.field-meta.xml
<CustomField>
    <fullName>SCV_Code__c</fullName>
    <description>+++ INTEGRATION: MASTER DATA +++
Do not change this field without reviewing impact with master data integration&quot; .
Unique customer number shared across numerous Maersk systems. Populated by custom Java components in the middleware layer. Should be read-only to users using FLS so there is no chance of modification by anyone other than the Master Data Interface User.
#RQ-002042-Reduced the text characters to 11
#RQ-004927.</description>
    <externalId>true</externalId>
    <inlineHelpText>Internal system identifier from SCV</inlineHelpText>
    <label>SCV Code</label>
    <length>11</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SCV_Status__c.field-meta.xml
<CustomField>
    <fullName>SCV_Status__c</fullName>
    <description>&quot;+++ INTEGRATION: MASTER DATA +++ 
Do not change this field without reviewing impact with master data integration&quot;
#RQ-000235 - Help text added.
#RQ-004162 - Changed Field label and help text
#RQ-004927.</description>
    <inlineHelpText>Indicates if this customer is active or not as per Customer Master Data definitions</inlineHelpText>
    <label>Customer Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchUpdateTerritoryAccAssoc_Test.cls
/**
 * This batch code is created to update records in Territory_Account_Association__c object as per SFSE-5588 story to update newly created fields. 
 * This class is of one-off use. Once new fields are updated in PROD then BatchUpdateTerritoryAccAssoc and BatchUpdateTerritoryAccAssoc_Test class should be deleted.
 * 
 * Version     Date         Owner                      RQ#            Description
 ******************************************************************************************************  
 * 1.0                                                 #              Code created
 * 2.0         07-06-2022   Ronnie@SF                  SPI-100        Removed brand hardcoding
 * 3.0         14-dec-2023     Bharti                 SFSE-13491     Remove hardcoding of Portfolio owner Responsibility
 */
@isTest(seeAllData=false)
public class BatchUpdateTerritoryAccAssoc_Test {
    
     @testSetup static void setup() {
         
         UserDataGeneratorHelper_Test.initializeSystemAdminUser();
         
         system.runAs(UserDataGeneratorHelper_Test.SystemAdminUser) {
         	TriggerExecutionController.skipAllTriggers(true);
             
         	// assign Liner Brand level access to user 
         	PermissionSet ps = [SELECT Id FROM PermissionSet WHERE Name = 'APP_Territory_Management_Manage_Portfolios'];
         	PermissionSetAssignment psa = new PermissionSetAssignment();
         	psa.AssigneeId = UserDataGeneratorHelper_Test.MSLSystemAdminUser.Id;
         	psa.PermissionSetId = ps.Id;       
         	insert psa;           
            
         	TriggerExecutionController.skipAllTriggers(false);
         }

         system.runas( UserDataGeneratorHelper_Test.MSLSystemAdminUser ) {
			 List<Account> lstConcernAccounts = new List<Account>();
             List<Account> lstClientAccounts = new List<Account>();
        	 
             AccountData_Test.iNumberOfAccounts = 1;
        	 AccountData_Test.createConcernAccounts();
        	 lstConcernAccounts =AccountData_Test.lstAccounts;
             lstConcernAccounts[0].SCV_Code__c = '***0112233';
             update lstConcernAccounts;
             
             AccountData_Test.iNumberOfAccounts = 1;
        	 AccountData_Test.createClientAccounts();
             lstClientAccounts = AccountData_Test.lstAccounts;
             lstClientAccounts[0].ParentId = lstConcernAccounts[0].Id;
             lstClientAccounts[0].Represents_Concern__c = TRUE;
             lstClientAccounts[0].SCV_Status__c = 'Active';
             update lstClientAccounts;
             
             List<Territory__c> lstInsertTerritory = new List<Territory__c>();
        	 lstInsertTerritory.add(TerritoryDataGeneration_Test.createPortfolio('MSLTest1-PortfolioTerritory', UserInfo.getUserId()));
             insert(lstInsertTerritory); 
             
             List<Territory_Account_Association__c> lstInsert = new List<Territory_Account_Association__c>();
             lstInsert.add( TerritoryDataGeneration_Test.addAccountToPortfolio(lstInsertTerritory[0].Id, lstClientAccounts[0].Id, BrandUtilities.MAERSKLINE, TAASettingConstants.POR_SALES_CONTROL));
             insert lstInsert;
         }
    }
    
    @isTest static void testBatch() {
        
        Test.startTest();
        BatchUpdateTerritoryAccAssoc batchTest = new BatchUpdateTerritoryAccAssoc();
        Database.executeBatch(batchTest); 
        Test.stopTest();
        
        List<Territory_Account_Association__c> lstTAA = [SELECT Id, Account_Concern_Code__c FROM Territory_Account_Association__c WHERE Account_Concern_Code__c = null];
        System.assertEquals(lstTAA.size(), 0);
    }
}